using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Net;
using System.IO;
using System.Text.RegularExpressions;
using System.Runtime.InteropServices;
using System.Threading;

namespace _TrainQuery_
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        Dictionary<string,string> dic=new Dictionary<string,string>();
        List<Tickets> lst_ticketsPart = new List<Tickets>();
        /// <summary>
        /// 初始化
        /// </summary>
        private void Form1_Load(object sender, EventArgs e)
        {
            dtp.MaxDate = DateTime.Now.AddDays(26);
            dtp.MinDate = DateTime.Now;
            Thread t1=new Thread(()=>{DicLoad();});
            t1.IsBackground=true;
            t1.Start();

            Thread t2 = new Thread(() => { InternetConState(); });
            t2.IsBackground = true;
            t2.Start();
        }
        //判断当前网络或者网站改变地址自己判断，其实无所谓
        private void btnSearch_Click(object sender, EventArgs e)
        {
            btnSearch.Enabled = false;
            Thread t3 = new Thread(() => { Execute(); });
            t3.IsBackground = true;
            t3.Start();
        }

        //执行查询
        private void Execute()
        {
            if (dic.Count < 1000)
            {
                return;
            }
            //获取页面json
            string from = "";
            string to = "";
            Invoke(new Action(() =>
            {
                from = JsonSearch(dic, txtDesFrom.Text.Trim());
                to = JsonSearch(dic, txtDesTo.Text.Trim());
            }));
            if (from == "0" || from == "-1" || to == "0" || to == "-1")
            {
                return;//错误
            }
            string date = dtp.Value.ToString("yyyy-MM-dd");
            string url = "https://kyfw.12306.cn/otn/lcxxcx/query" + "?purpose_codes=ADULT"
                + "&queryDate=" + date + "&from_station=" + from + "&to_station=" + to;
            string json = GetResponseHtml(url, "get", "", "application/x-www-form-urlencoded", "utf-8");
            //处理返回的json
            string[] strTickets = JsonHelp(json);//每行一组票况
            if (strTickets==null)//2014-1-8购票高峰期间服务器崩溃会返回错误字段,此处处理
            {
                Invoke(new Action(() => {
                    btnSearch.Enabled = true;
                }));

                return;
            }
            else
            {
                List<Tickets> lst_tickets = new List<Tickets>();
                for (int i = 0; i < strTickets.Length; i++)
                {
                    Tickets tk = new Tickets();
                    tk = JsonTicket(strTickets[i]);
                    lst_tickets.Add(tk);
                }
                Invoke(new Action(() =>
                {
                    lst_ticketsPart = lst_tickets;
                    dataGridView1.DataSource = lst_tickets;
                    //dataGridView1.
                    //隐藏列
                    dataGridView1.Columns["train_no"].Visible = false;
                    dataGridView1.Columns["start_station_telecode"].Visible = false;
                    dataGridView1.Columns["end_station_telecode"].Visible = false;
                    dataGridView1.Columns["from_station_telecode"].Visible = false;
                    dataGridView1.Columns["start_station_name"].Visible = false;
                    dataGridView1.Columns["end_station_name"].Visible = false;
                    dataGridView1.Columns["train_no"].Visible = false;
                    dataGridView1.Columns["to_station_telecode"].Visible = false;

                    dataGridView1.Columns["day_difference"].Visible = false;
                    dataGridView1.Columns["train_class_name"].Visible = false;
                    dataGridView1.Columns["canWebBuy"].Visible = false;
                    dataGridView1.Columns["lishiValue"].Visible = false;
                    dataGridView1.Columns["yp_info"].Visible = false;
                    dataGridView1.Columns["control_train_day"].Visible = false;
                    dataGridView1.Columns["start_train_date"].Visible = false;
                    dataGridView1.Columns["seat_feature"].Visible = false;

                    dataGridView1.Columns["yp_ex"].Visible = false;
                    dataGridView1.Columns["train_seat_feature"].Visible = false;
                    dataGridView1.Columns["seat_types"].Visible = false;
                    dataGridView1.Columns["location_code"].Visible = false;
                    dataGridView1.Columns["from_station_no"].Visible = false;
                    dataGridView1.Columns["to_station_no"].Visible = false;
                    dataGridView1.Columns["start_train_date"].Visible = false;
                    dataGridView1.Columns["control_day"].Visible = false;

                    dataGridView1.Columns["sale_time"].Visible = false;
                    dataGridView1.Columns["is_support_card"].Visible = false;
                    dataGridView1.Columns["note"].Visible = false;
                    dataGridView1.Columns["gg_num"].Visible = false;
                    //dataGridView1.Columns["location_code"].Visible = false;
                    //dataGridView1.Columns["from_station_no"].Visible = false;
                    //dataGridView1.Columns["to_station_no"].Visible = false;
                    //dataGridView1.Columns["start_train_date"].Visible = false;
                    //dataGridView1.Columns["control_day"].Visible = false;    

                    lbListCount.Text = dataGridView1.Rows.Count.ToString() + " 辆";
                    btnSearch.Enabled = true;
                }));
            }
        }
           

        private void CbChange(object sender, EventArgs e)
        {
                //List<Tickets> lst_tickets=new List<Tickets>();
                /*
                var tickets=0;
                string ticketNo="";
                foreach (var item in gbTrainNo.Controls)
	            {
		             if (item is CheckBox)
	                {
		                  ticketNo+=((CheckBox)item).Tag+"|";
	                }
                }
                string[] ticketNos=JsonCut(ticketNo,"|");
                int ticketNosLen=ticketNos.Length;
                if (ticketNosLen>0)
	            {
                    var result=0;
                    for (int i = 0; i < ticketNosLen; i++)
			        {
                        result+=lst_ticketsPart.Where(p=>p.train_no.StartsWith(ticketNos[i]));
			        }
	            }

                if(cbG.Checked)
                {
                    tickets=lst_ticketsPart.Where(p=>p.train_no.StartsWith("G"));
                }
                if (cbD.Checked){trainno+="D|";}
                if(cbZ.Checked){trainno+="Z"}
                */
            //}
        }

        #region 获取返回的Json或html，提交数据
        /// <summary>
        /// 获取返回的Json或html，提交数据
        /// </summary>
        /// <param name="url">提交的地址</param>
        /// <param name="method">"POST"或者"GET"</param>
        /// <param name="data">当method为"POST"时，data会被提交到服务器；当method是"GET"时,data应该为空(string.empty)</param>
        /// <param name="contenttype">Content-Type HTTP的标头值，例如:返回json:"application/json; charset=utf8";返回web:"application/x-www-form-urlencoded"</param>
        /// <param name="encoding">提交后响应的文章编码</param>
        /// <returns>返回服务器响应的数据</returns>
        public string GetResponseHtml(string url, string method, string data, string contenttype, string encoding)
        {
            string IE7 = "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; InfoPath.2; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022; .NET4.0C; .NET4.0E)";
            try
            {
                HttpWebRequest req = (HttpWebRequest)WebRequest.Create(url);
                req.KeepAlive = true;
                req.Method = method.ToUpper();
                req.AllowAutoRedirect = true;
                //req.ContentType = "application/json; charset=utf8";
                req.ContentType = contenttype.ToString();

                req.UserAgent = IE7;
                req.Accept = "application/json, text/javascript, */*; q=0.01";
                req.Timeout = 50000;


                if (method.ToUpper() == "POST" && data != null)
                {
                    ASCIIEncoding encodings = new ASCIIEncoding();
                    byte[] postBytes = encodings.GetBytes(data); ;
                    req.ContentLength = postBytes.Length;
                    Stream st = req.GetRequestStream();
                    st.Write(postBytes, 0, postBytes.Length);
                    st.Close();
                }

                System.Net.ServicePointManager.ServerCertificateValidationCallback += (se, cert, chain, sslerror) =>
                {
                    return true;
                };

                Encoding myEncoding = Encoding.GetEncoding(encoding);//编码

                HttpWebResponse res = (HttpWebResponse)req.GetResponse();
                Stream resst = res.GetResponseStream();
                StreamReader sr = new StreamReader(resst, myEncoding);
                string str = sr.ReadToEnd();

                return str;
            }
            catch (Exception)
            {
                return "";
            }
        }

        #endregion

        #region 查询站名对应的编号
        /// <summary>
        /// 查询传入的json数据，得到结果值(单层有效)
        /// </summary>
        /// <param name="data">json数据</param>
        /// <param name="key">要查询的key(没有返回-1)</param>
        /// <returns>返回查询结果</returns>
        public string JsonSearch(Dictionary<string, string> dic, string key)
        {
            try
            {
                if (dic.Count > 0)
                {
                    return dic[key];
                }
                return "0";
            }
            catch (Exception err)
            {
                return "-1";
            }
        }
        /// <summary>
        /// 启动时初始化字典库
        /// </summary>
        /// <returns></returns>
        public void DicLoad()
        { 
            //Dictionary<string, string> dic = new Dictionary<string, string>();
            #region 添加站名,代号
            dic.Add("北京北", "VAP");
            dic.Add("北京东", "BOP");
            dic.Add("北京", "BJP");
            dic.Add("北京南", "VNP");
            dic.Add("北京西", "BXP");
            dic.Add("重庆北", "CUW");
            dic.Add("重庆", "CQW");
            dic.Add("重庆南", "CRW");
            dic.Add("长春", "CCT");
            dic.Add("长春南", "CET");
            dic.Add("长春西", "CRT");
            dic.Add("成都东", "ICW");
            dic.Add("成都南", "CNW");
            dic.Add("成都", "CDW");
            dic.Add("长沙", "CSQ");
            dic.Add("长沙南", "CWQ");
            dic.Add("阿尔山", "ART");
            dic.Add("安康", "AKY");
            dic.Add("阿克苏", "ASR");
            dic.Add("阿里河", "AHX");
            dic.Add("阿拉山口", "AKR");
            dic.Add("安平", "APT");
            dic.Add("安庆", "AQH");
            dic.Add("安顺", "ASW");
            dic.Add("鞍山", "AST");
            dic.Add("安阳", "AYF");
            dic.Add("北安", "BAB");
            dic.Add("蚌埠", "BBH");
            dic.Add("白城", "BCT");
            dic.Add("北海", "BHZ");
            dic.Add("白河", "BEL");
            dic.Add("白涧", "BAP");
            dic.Add("宝鸡", "BJY");
            dic.Add("滨江", "BJB");
            dic.Add("博克图", "BKX");
            dic.Add("百色", "BIZ");
            dic.Add("白山市", "HJL");
            dic.Add("北台", "BTT");
            dic.Add("包头东", "BDC");
            dic.Add("包头", "BTC");
            dic.Add("北屯市", "BXR");
            dic.Add("本溪", "BXT");
            dic.Add("白云鄂博", "BEC");
            dic.Add("白银西", "BXJ");
            dic.Add("亳州", "BZH");
            dic.Add("赤壁", "CBN");
            dic.Add("常德", "VGQ");
            dic.Add("承德", "CDP");
            dic.Add("长甸", "CDT");
            dic.Add("赤峰", "CFD");
            dic.Add("茶陵", "CDG");
            dic.Add("苍南", "CEH");
            dic.Add("昌平", "CPP");
            dic.Add("崇仁", "CRG");
            dic.Add("昌图", "CTT");
            dic.Add("长汀镇", "CDB");
            dic.Add("崇信", "CIJ");
            dic.Add("曹县", "CXK");
            dic.Add("楚雄", "COM");
            dic.Add("陈相屯", "CXT");
            dic.Add("长治北", "CBF");
            dic.Add("长征", "CZJ");
            dic.Add("池州", "IYH");
            dic.Add("常州", "CZH");
            dic.Add("郴州", "CZQ");
            dic.Add("长治", "CZF");
            dic.Add("沧州", "COP");
            dic.Add("崇左", "CZZ");
            dic.Add("大安北", "RNT");
            dic.Add("大成", "DCT");
            dic.Add("丹东", "DUT");
            dic.Add("东方红", "DFB");
            dic.Add("东莞东", "DMQ");
            dic.Add("大虎山", "DHD");
            dic.Add("敦煌", "DHJ");
            dic.Add("敦化", "DHL");
            dic.Add("德惠", "DHT");
            dic.Add("东京城", "DJB");
            dic.Add("大涧", "DFP");
            dic.Add("都江堰", "DDW");
            dic.Add("大连北", "DFT");
            dic.Add("大理", "DKM");
            dic.Add("大连", "DLT");
            dic.Add("定南", "DNG");
            dic.Add("大庆", "DZX");
            dic.Add("东胜", "DOC");
            dic.Add("大石桥", "DQT");
            dic.Add("大同", "DTV");
            dic.Add("东营", "DPK");
            dic.Add("大杨树", "DUX");
            dic.Add("都匀", "RYW");
            dic.Add("邓州", "DOF");
            dic.Add("达州", "RXW");
            dic.Add("德州", "DZP");
            dic.Add("额济纳", "EJC");
            dic.Add("二连", "RLC");
            dic.Add("恩施", "ESN");
            dic.Add("昂昂溪", "AAX");
            dic.Add("阿城", "ACB");
            dic.Add("安达", "ADX");
            dic.Add("安定", "ADP");
            dic.Add("安广", "AGT");
            dic.Add("艾河", "AHP");
            dic.Add("安化", "PKQ");
            dic.Add("艾家村", "AJJ");
            dic.Add("鳌江", "ARH");
            dic.Add("安家", "AJB");
            dic.Add("阿金", "AJD");
            dic.Add("阿克陶", "AER");
            dic.Add("安口窑", "AYY");
            dic.Add("敖力布告", "ALD");
            dic.Add("安龙", "AUZ");
            dic.Add("阿龙山", "ASX");
            dic.Add("安陆", "ALN");
            dic.Add("阿木尔", "JTX");
            dic.Add("阿南庄", "AZM");
            dic.Add("安庆西", "APH");
            dic.Add("鞍山西", "AXT");
            dic.Add("安塘", "ATV");
            dic.Add("安亭北", "ASH");
            dic.Add("阿图什", "ATR");
            dic.Add("安图", "ATL");
            dic.Add("安溪", "AXS");
            dic.Add("博鳌", "BWQ");
            dic.Add("白壁关", "BGV");
            dic.Add("蚌埠南", "BMH");
            dic.Add("巴楚", "BCR");
            dic.Add("板城", "BUP");
            dic.Add("北戴河", "BEP");
            dic.Add("保定", "BDP");
            dic.Add("宝坻", "BPP");
            dic.Add("八达岭", "ILP");
            dic.Add("巴东", "BNN");
            dic.Add("柏果", "BGM");
            dic.Add("布海", "BUT");
            dic.Add("白河东", "BIY");
            dic.Add("贲红", "BVC");
            dic.Add("宝华山", "BWH");
            dic.Add("白河县", "BEY");
            dic.Add("白芨沟", "BJJ");
            dic.Add("碧鸡关", "BJM");
            dic.Add("北滘", "IBQ");
            dic.Add("碧江", "BLQ");
            dic.Add("白鸡坡", "BBM");
            dic.Add("笔架山", "BSB");
            dic.Add("八角台", "BTD");
            dic.Add("保康", "BKD");
            dic.Add("白奎堡", "BKB");
            dic.Add("白狼", "BAT");
            dic.Add("百浪", "BRZ");
            dic.Add("博乐", "BOR");
            dic.Add("宝拉格", "BQC");
            dic.Add("巴林", "BLX");
            dic.Add("宝林", "BNB");
            dic.Add("北流", "BOZ");
            dic.Add("勃利", "BLB");
            dic.Add("布列开", "BLR");
            dic.Add("宝龙山", "BND");
            dic.Add("八面城", "BMD");
            dic.Add("班猫箐", "BNM");
            dic.Add("八面通", "BMB");
            dic.Add("北马圈子", "BRP");
            dic.Add("北票南", "RPD");
            dic.Add("白旗", "BQP");
            dic.Add("宝泉岭", "BQB");
            dic.Add("白泉", "BQL");
            dic.Add("白沙", "BSW");
            dic.Add("巴山", "BAY");
            dic.Add("白水江", "BSY");
            dic.Add("白沙坡", "BPM");
            dic.Add("白石山", "BAL");
            dic.Add("白水镇", "BUM");
            dic.Add("坂田", "BTQ");
            dic.Add("泊头", "BZP");
            dic.Add("北屯", "BYP");
            dic.Add("本溪湖", "BHT");
            dic.Add("博兴", "BXK");
            dic.Add("八仙筒", "VXD");
            dic.Add("白音察干", "BYC");
            dic.Add("背荫河", "BYB");
            dic.Add("北营", "BIV");
            dic.Add("巴彦高勒", "BAC");
            dic.Add("白音他拉", "BID");
            dic.Add("鲅鱼圈", "BYT");
            dic.Add("白银市", "BNJ");
            dic.Add("白音胡硕", "BCD");
            dic.Add("巴中", "IEW");
            dic.Add("霸州", "RMP");
            dic.Add("北宅", "BVP");
            dic.Add("赤壁北", "CIN");
            dic.Add("查布嘎", "CBC");
            dic.Add("长城", "CEJ");
            dic.Add("长冲", "CCM");
            dic.Add("承德东", "CCP");
            dic.Add("赤峰西", "CID");
            dic.Add("嵯岗", "CAX");
            dic.Add("柴岗", "CGT");
            dic.Add("长葛", "CEF");
            dic.Add("柴沟堡", "CGV");
            dic.Add("城固", "CGY");
            dic.Add("陈官营", "CAJ");
            dic.Add("成高子", "CZB");
            dic.Add("草海", "WBW");
            dic.Add("柴河", "CHB");
            dic.Add("册亨", "CHZ");
            dic.Add("草河口", "CKT");
            dic.Add("崔黄口", "CHP");
            dic.Add("巢湖", "CIH");
            dic.Add("蔡家沟", "CJT");
            dic.Add("成吉思汗", "CJX");
            dic.Add("岔江", "CAM");
            dic.Add("蔡家坡", "CJY");
            dic.Add("沧口", "CKK");
            dic.Add("昌乐", "CLK");
            dic.Add("超梁沟", "CYP");
            dic.Add("慈利", "CUQ");
            dic.Add("昌黎", "CLP");
            dic.Add("长岭子", "CLT");
            dic.Add("晨明", "CMB");
            dic.Add("长农", "CNJ");
            dic.Add("昌平北", "VBP");
            dic.Add("长坡岭", "CPM");
            dic.Add("辰清", "CQB");
            dic.Add("楚山", "CSB");
            dic.Add("长寿", "EFW");
            dic.Add("磁山", "CSP");
            dic.Add("苍石", "CST");
            dic.Add("草市", "CSL");
            dic.Add("察素齐", "CSC");
            dic.Add("长山屯", "CVT");
            dic.Add("长汀", "CES");
            dic.Add("昌图西", "CPT");
            dic.Add("春湾", "CQQ");
            dic.Add("磁县", "CIP");
            dic.Add("岑溪", "CNZ");
            dic.Add("辰溪", "CXQ");
            dic.Add("磁西", "CRP");
            dic.Add("长兴南", "CFH");
            dic.Add("磁窑", "CYK");
            dic.Add("朝阳", "CYD");
            dic.Add("春阳", "CAL");
            dic.Add("城阳", "CEK");
            dic.Add("创业村", "CEX");
            dic.Add("朝阳川", "CYL");
            dic.Add("朝阳地", "CDD");
            dic.Add("长垣", "CYF");
            dic.Add("朝阳镇", "CZL");
            dic.Add("滁州北", "CUH");
            dic.Add("常州北", "ESH");
            dic.Add("滁州", "CXH");
            dic.Add("潮州", "CKQ");
            dic.Add("常庄", "CVK");
            dic.Add("曹子里", "CFP");
            dic.Add("车转湾", "CWM");
            dic.Add("郴州西", "ICQ");
            dic.Add("沧州西", "CBP");
            dic.Add("德安", "DAG");
            dic.Add("大安", "RAT");
            dic.Add("东安", "DAZ");
            dic.Add("大坝", "DBJ");
            dic.Add("大板", "DBC");
            dic.Add("大巴", "DBD");
            dic.Add("到保", "RBT");
            dic.Add("定边", "DYJ");
            dic.Add("东边井", "DBB");
            dic.Add("德伯斯", "RDT");
            dic.Add("打柴沟", "DGJ");
            dic.Add("德昌", "DVW");
            dic.Add("滴道", "DDB");
            dic.Add("大德", "DEM");
            dic.Add("大磴沟", "DKJ");
            dic.Add("刀尔登", "DRD");
            dic.Add("得耳布尔", "DRX");
            dic.Add("东方", "UFQ");
            dic.Add("丹凤", "DGY");
            dic.Add("东丰", "DIL");
            dic.Add("都格", "DMM");
            dic.Add("大官屯", "DTT");
            dic.Add("大关", "RGW");
            dic.Add("东光", "DGP");
            dic.Add("东莞", "DAQ");
            dic.Add("东海", "DHB");
            dic.Add("大灰厂", "DHP");
            dic.Add("大红旗", "DQD");
            dic.Add("东海县", "DQH");
            dic.Add("德惠西", "DXT");
            dic.Add("达家沟", "DJT");
            dic.Add("东津", "DKB");
            dic.Add("杜家", "DJL");
            dic.Add("大旧庄", "DJM");
            dic.Add("大口屯", "DKP");
            dic.Add("东来", "RVD");
            dic.Add("德令哈", "DHO");
            dic.Add("大陆号", "DLC");
            dic.Add("带岭", "DLB");
            dic.Add("大林", "DLD");
            dic.Add("达拉特旗", "DIC");
            dic.Add("独立屯", "DTX");
            dic.Add("豆罗", "DLV");
            dic.Add("达拉特西", "DNC");
            dic.Add("东明村", "DMD");
            dic.Add("洞庙河", "DEP");
            dic.Add("东明县", "DNF");
            dic.Add("大拟", "DNZ");
            dic.Add("大平房", "DPD");
            dic.Add("大盘石", "RPP");
            dic.Add("大埔", "DPI");
            dic.Add("大堡", "DVT");
            dic.Add("大其拉哈", "DQX");
            dic.Add("道清", "DML");
            dic.Add("对青山", "DQB");
            dic.Add("德清西", "MOH");
            dic.Add("东升", "DRQ");
            dic.Add("独山", "RWW");
            dic.Add("砀山", "DKH");
            dic.Add("登沙河", "DWT");
            dic.Add("读书铺", "DPM");
            dic.Add("大石头", "DSL");
            dic.Add("大石寨", "RZT");
            dic.Add("东台", "DBH");
            dic.Add("定陶", "DQK");
            dic.Add("灯塔", "DGT");
            dic.Add("大田边", "DBM");
            dic.Add("东通化", "DTL");
            dic.Add("丹徒", "RUH");
            dic.Add("大屯", "DNT");
            dic.Add("东湾", "DRJ");
            dic.Add("大武口", "DFJ");
            dic.Add("低窝铺", "DWJ");
            dic.Add("大王滩", "DZZ");
            dic.Add("大湾子", "DFM");
            dic.Add("大兴沟", "DXL");
            dic.Add("大兴", "DXX");
            dic.Add("定西", "DSJ");
            dic.Add("甸心", "DXM");
            dic.Add("东乡", "DXG");
            dic.Add("代县", "DKV");
            dic.Add("定襄", "DXV");
            dic.Add("东戌", "RXP");
            dic.Add("东辛庄", "DXD");
            dic.Add("丹阳", "DYH");
            dic.Add("大雁", "DYX");
            dic.Add("德阳", "DYW");
            dic.Add("当阳", "DYN");
            dic.Add("丹阳北", "EXH");
            dic.Add("大英东", "IAW");
            dic.Add("东淤地", "DBV");
            dic.Add("大营", "DYV");
            dic.Add("定远", "EWH");
            dic.Add("岱岳", "RYV");
            dic.Add("大元", "DYZ");
            dic.Add("大营镇", "DJP");
            dic.Add("大营子", "DZD");
            dic.Add("大战场", "DTJ");
            dic.Add("德州东", "DIP");
            dic.Add("低庄", "DVQ");
            dic.Add("东镇", "DNV");
            dic.Add("道州", "DFZ");
            dic.Add("东至", "DCH");
            dic.Add("东庄", "DZV");
            dic.Add("兑镇", "DWV");
            dic.Add("豆庄", "ROP");
            dic.Add("定州", "DXP");
            dic.Add("大竹园", "DZY");
            dic.Add("大杖子", "DAP");
            dic.Add("豆张庄", "RZP");
            dic.Add("峨边", "EBW");
            dic.Add("二道沟门", "RDP");
            dic.Add("二道湾", "RDX");
            dic.Add("二龙", "RLD");
            dic.Add("二龙山屯", "ELA");
            dic.Add("峨眉", "EMW");
            dic.Add("二密河", "RML");
            dic.Add("二营", "RYJ");
            dic.Add("鄂州", "ECN");
            dic.Add("安阳东", "ADF");
            dic.Add("保定东", "BMP");
            dic.Add("长阳", "CYN");
            dic.Add("东二道河", "DRB");
            dic.Add("大苴", "DIM");
            dic.Add("大青沟", "DSD");
            dic.Add("定州东", "DOP");
            dic.Add("福州", "FZS");
            dic.Add("福州南", "FYS");
            dic.Add("贵阳", "GIW");
            dic.Add("广州北", "GBQ");
            dic.Add("广州东", "GGQ");
            dic.Add("广州", "GZQ");
            dic.Add("广州南", "IZQ");
            dic.Add("哈尔滨", "HBB");
            dic.Add("哈尔滨东", "VBB");
            dic.Add("哈尔滨西", "VAB");
            dic.Add("合肥", "HFH");
            dic.Add("合肥西", "HTH");
            dic.Add("呼和浩特东", "NDC");
            dic.Add("呼和浩特", "HHC");
            dic.Add("海口东", "HMQ");
            dic.Add("海口", "VUQ");
            dic.Add("杭州", "HZH");
            dic.Add("杭州南", "XHH");
            dic.Add("济南", "JNK");
            dic.Add("济南东", "JAK");
            dic.Add("济南西", "JGK");
            dic.Add("防城港", "FEZ");
            dic.Add("福鼎", "FES");
            dic.Add("风陵渡", "FLV");
            dic.Add("涪陵", "FLW");
            dic.Add("富拉尔基", "FRX");
            dic.Add("抚顺北", "FET");
            dic.Add("佛山", "FSQ");
            dic.Add("阜新", "FXD");
            dic.Add("阜阳", "FYH");
            dic.Add("格尔木", "GRO");
            dic.Add("广汉", "GHW");
            dic.Add("古交", "GJV");
            dic.Add("桂林北", "GBZ");
            dic.Add("古莲", "GRX");
            dic.Add("桂林", "GLZ");
            dic.Add("固始", "GXN");
            dic.Add("广水", "GSN");
            dic.Add("干塘", "GNJ");
            dic.Add("广元", "GYW");
            dic.Add("赣州", "GZG");
            dic.Add("公主岭", "GLT");
            dic.Add("公主岭南", "GBT");
            dic.Add("淮安", "AUH");
            dic.Add("鹤北", "HMB");
            dic.Add("淮北", "HRH");
            dic.Add("淮滨", "HVN");
            dic.Add("河边", "HBV");
            dic.Add("潢川", "KCN");
            dic.Add("韩城", "HCY");
            dic.Add("邯郸", "HDP");
            dic.Add("横道河子", "HDB");
            dic.Add("鹤岗", "HGB");
            dic.Add("皇姑屯", "HTT");
            dic.Add("红果", "HEM");
            dic.Add("黑河", "HJB");
            dic.Add("怀化", "HHQ");
            dic.Add("汉口", "HKN");
            dic.Add("葫芦岛", "HLD");
            dic.Add("海拉尔", "HRX");
            dic.Add("霍林郭勒", "HWD");
            dic.Add("海伦", "HLB");
            dic.Add("侯马", "HMV");
            dic.Add("哈密", "HMR");
            dic.Add("淮南", "HAH");
            dic.Add("桦南", "HNB");
            dic.Add("海宁西", "EUH");
            dic.Add("鹤庆", "HQM");
            dic.Add("怀柔北", "HBP");
            dic.Add("怀柔", "HRP");
            dic.Add("黄石东", "OSN");
            dic.Add("华山", "HSY");
            dic.Add("黄石", "HSN");
            dic.Add("黄山", "HKH");
            dic.Add("衡水", "HSP");
            dic.Add("衡阳", "HYQ");
            dic.Add("菏泽", "HIK");
            dic.Add("贺州", "HXZ");
            dic.Add("汉中", "HOY");
            dic.Add("惠州", "HCQ");
            dic.Add("吉安", "VAG");
            dic.Add("集安", "JAL");
            dic.Add("江边村", "JBG");
            dic.Add("晋城", "JCF");
            dic.Add("金城江", "JJZ");
            dic.Add("景德镇", "JCG");
            dic.Add("嘉峰", "JFF");
            dic.Add("加格达奇", "JGX");
            dic.Add("井冈山", "JGG");
            dic.Add("蛟河", "JHL");
            dic.Add("金华南", "RNH");
            dic.Add("金华西", "JBH");
            dic.Add("九江", "JJG");
            dic.Add("吉林", "JLL");
            dic.Add("荆门", "JMN");
            dic.Add("佳木斯", "JMB");
            dic.Add("济宁", "JIK");
            dic.Add("集宁南", "JAC");
            dic.Add("酒泉", "JQJ");
            dic.Add("江山", "JUH");
            dic.Add("吉首", "JIQ");
            dic.Add("九台", "JTL");
            dic.Add("镜铁山", "JVJ");
            dic.Add("鸡西", "JXB");
            dic.Add("蓟县", "JKP");
            dic.Add("绩溪县", "JRH");
            dic.Add("嘉峪关", "JGJ");
            dic.Add("江油", "JFW");
            dic.Add("锦州", "JZD");
            dic.Add("金州", "JZT");
            dic.Add("福安", "FAS");
            dic.Add("防城", "FAZ");
            dic.Add("丰城", "FCG");
            dic.Add("丰城南", "FNG");
            dic.Add("肥东", "FIH");
            dic.Add("发耳", "FEM");
            dic.Add("富海", "FHX");
            dic.Add("福海", "FHR");
            dic.Add("凤凰城", "FHT");
            dic.Add("奉化", "FHH");
            dic.Add("富锦", "FIB");
            dic.Add("范家屯", "FTT");
            dic.Add("福利屯", "FTB");
            dic.Add("丰乐镇", "FZB");
            dic.Add("阜南", "FNH");
            dic.Add("阜宁", "AKH");
            dic.Add("抚宁", "FNP");
            dic.Add("福清", "FQS");
            dic.Add("福泉", "VMW");
            dic.Add("丰水村", "FSJ");
            dic.Add("丰顺", "FUQ");
            dic.Add("繁峙", "FSV");
            dic.Add("抚顺", "FST");
            dic.Add("福山口", "FKP");
            dic.Add("扶绥", "FSZ");
            dic.Add("冯屯", "FTX");
            dic.Add("浮图峪", "FYP");
            dic.Add("富县东", "FDY");
            dic.Add("凤县", "FXY");
            dic.Add("富县", "FEY");
            dic.Add("费县", "FXK");
            dic.Add("凤阳", "FUH");
            dic.Add("汾阳", "FAV");
            dic.Add("扶余北", "FBT");
            dic.Add("分宜", "FYG");
            dic.Add("富源", "FYM");
            dic.Add("扶余", "FYT");
            dic.Add("富裕", "FYX");
            dic.Add("抚州北", "FBG");
            dic.Add("凤州", "FZY");
            dic.Add("丰镇", "FZC");
            dic.Add("范镇", "VZK");
            dic.Add("固安", "GFP");
            dic.Add("广安", "VJW");
            dic.Add("高碑店", "GBP");
            dic.Add("沟帮子", "GBD");
            dic.Add("甘草店", "GDJ");
            dic.Add("谷城", "GCN");
            dic.Add("藁城", "GEP");
            dic.Add("高村", "GCV");
            dic.Add("古城镇", "GZB");
            dic.Add("广德", "GRH");
            dic.Add("贵定", "GTW");
            dic.Add("贵定南", "IDW");
            dic.Add("古东", "GDV");
            dic.Add("贵港", "GGZ");
            dic.Add("官高", "GVP");
            dic.Add("葛根庙", "GGT");
            dic.Add("干沟", "GGL");
            dic.Add("甘谷", "GGJ");
            dic.Add("高各庄", "GGP");
            dic.Add("甘河", "GAX");
            dic.Add("根河", "GEX");
            dic.Add("郭家店", "GDT");
            dic.Add("孤家子", "GKT");
            dic.Add("高老", "GOB");
            dic.Add("古浪", "GLJ");
            dic.Add("皋兰", "GEJ");
            dic.Add("高楼房", "GFM");
            dic.Add("归流河", "GHT");
            dic.Add("关林", "GLF");
            dic.Add("甘洛", "VOW");
            dic.Add("郭磊庄", "GLP");
            dic.Add("高密", "GMK");
            dic.Add("公庙子", "GMC");
            dic.Add("工农湖", "GRT");
            dic.Add("广宁寺", "GNT");
            dic.Add("广南卫", "GNM");
            dic.Add("高平", "GPF");
            dic.Add("甘泉北", "GEY");
            dic.Add("共青城", "GAG");
            dic.Add("甘旗卡", "GQD");
            dic.Add("甘泉", "GQY");
            dic.Add("高桥镇", "GZD");
            dic.Add("赶水", "GSW");
            dic.Add("灌水", "GST");
            dic.Add("孤山口", "GSP");
            dic.Add("果松", "GSL");
            dic.Add("高山子", "GSD");
            dic.Add("嘎什甸子", "GXD");
            dic.Add("高台", "GTJ");
            dic.Add("高滩", "GAY");
            dic.Add("古田", "GTS");
            dic.Add("官厅", "GTP");
            dic.Add("广通", "GOM");
            dic.Add("官厅西", "KEP");
            dic.Add("贵溪", "GXG");
            dic.Add("涡阳", "GYH");
            dic.Add("巩义", "GXF");
            dic.Add("高邑", "GIP");
            dic.Add("巩义南", "GYF");
            dic.Add("固原", "GUJ");
            dic.Add("菇园", "GYL");
            dic.Add("公营子", "GYD");
            dic.Add("光泽", "GZS");
            dic.Add("古镇", "GNQ");
            dic.Add("瓜州", "GZJ");
            dic.Add("高州", "GSQ");
            dic.Add("固镇", "GEH");
            dic.Add("盖州", "GXT");
            dic.Add("官字井", "GOT");
            dic.Add("革镇堡", "GZT");
            dic.Add("冠豸山", "GSS");
            dic.Add("盖州西", "GAT");
            dic.Add("红安", "HWN");
            dic.Add("淮安南", "AMH");
            dic.Add("红安西", "VXN");
            dic.Add("海安县", "HIH");
            dic.Add("黄柏", "HBL");
            dic.Add("海北", "HEB");
            dic.Add("鹤壁", "HAF");
            dic.Add("华城", "VCQ");
            dic.Add("合川", "WKW");
            dic.Add("河唇", "HCZ");
            dic.Add("汉川", "HCN");
            dic.Add("海城", "HCT");
            dic.Add("黑冲滩", "HCJ");
            dic.Add("黄村", "HCP");
            dic.Add("海城西", "HXT");
            dic.Add("化德", "HGC");
            dic.Add("洪洞", "HDV");
            dic.Add("横峰", "HFG");
            dic.Add("韩府湾", "HXJ");
            dic.Add("汉沽", "HGP");
            dic.Add("黄瓜园", "HYM");
            dic.Add("红光镇", "IGW");
            dic.Add("浑河", "HHT");
            dic.Add("红花沟", "VHD");
            dic.Add("黄花筒", "HUD");
            dic.Add("贺家店", "HJJ");
            dic.Add("和静", "HJR");
            dic.Add("红江", "HFM");
            dic.Add("黑井", "HIM");
            dic.Add("获嘉", "HJF");
            dic.Add("河津", "HJV");
            dic.Add("涵江", "HJS");
            dic.Add("华家", "HJT");
            dic.Add("河间西", "HXP");
            dic.Add("花家庄", "HJM");
            dic.Add("河口南", "HKJ");
            dic.Add("黄口", "KOH");
            dic.Add("湖口", "HKG");
            dic.Add("呼兰", "HUB");
            dic.Add("葫芦岛北", "HPD");
            dic.Add("浩良河", "HHB");
            dic.Add("哈拉海", "HIT");
            dic.Add("鹤立", "HOB");
            dic.Add("桦林", "HIB");
            dic.Add("黄陵", "ULY");
            dic.Add("海林", "HRB");
            dic.Add("虎林", "VLB");
            dic.Add("寒岭", "HAT");
            dic.Add("和龙", "HLL");
            dic.Add("海龙", "HIL");
            dic.Add("哈拉苏", "HAX");
            dic.Add("呼鲁斯太", "VTJ");
            dic.Add("火连寨", "HLT");
            dic.Add("黄梅", "VEH");
            dic.Add("蛤蟆塘", "HMT");
            dic.Add("韩麻营", "HYP");
            dic.Add("黄泥河", "HHL");
            dic.Add("海宁", "HNH");
            dic.Add("惠农", "HMJ");
            dic.Add("和平", "VAQ");
            dic.Add("花棚子", "HZM");
            dic.Add("花桥", "VQH");
            dic.Add("宏庆", "HEY");
            dic.Add("怀仁", "HRV");
            dic.Add("华容", "HRN");
            dic.Add("华山北", "HDY");
            dic.Add("黄松甸", "HDL");
            dic.Add("和什托洛盖", "VSR");
            dic.Add("红山", "VSB");
            dic.Add("汉寿", "VSQ");
            dic.Add("衡山", "HSQ");
            dic.Add("黑水", "HOT");
            dic.Add("惠山", "VCH");
            dic.Add("虎什哈", "HHP");
            dic.Add("红寺堡", "HSJ");
            dic.Add("虎石台", "HUT");
            dic.Add("海石湾", "HSO");
            dic.Add("衡山西", "HEQ");
            dic.Add("红砂岘", "VSJ");
            dic.Add("黑台", "HQB");
            dic.Add("桓台", "VTK");
            dic.Add("和田", "VTR");
            dic.Add("会同", "VTQ");
            dic.Add("海坨子", "HZT");
            dic.Add("黑旺", "HWK");
            dic.Add("海湾", "RWH");
            dic.Add("红星", "VXB");
            dic.Add("徽县", "HYY");
            dic.Add("红兴隆", "VHB");
            dic.Add("换新天", "VTB");
            dic.Add("红岘台", "HTJ");
            dic.Add("红彦", "VIX");
            dic.Add("合阳", "HAY");
            dic.Add("海阳", "HYK");
            dic.Add("衡阳东", "HVQ");
            dic.Add("华蓥", "HUW");
            dic.Add("汉阴", "HQY");
            dic.Add("黄羊滩", "HGJ");
            dic.Add("汉源", "WHW");
            dic.Add("湟源", "HNO");
            dic.Add("河源", "VIQ");
            dic.Add("花园", "HUN");
            dic.Add("黄羊镇", "HYJ");
            dic.Add("化州", "HZZ");
            dic.Add("黄州", "VON");
            dic.Add("霍州", "HZV");
            dic.Add("惠州西", "VXQ");
            dic.Add("巨宝", "JRT");
            dic.Add("靖边", "JIY");
            dic.Add("金宝屯", "JBD");
            dic.Add("晋城北", "JEF");
            dic.Add("金昌", "JCJ");
            dic.Add("鄄城", "JCK");
            dic.Add("交城", "JNV");
            dic.Add("建昌", "JFD");
            dic.Add("峻德", "JDB");
            dic.Add("井店", "JFP");
            dic.Add("鸡东", "JOB");
            dic.Add("江都", "UDH");
            dic.Add("鸡冠山", "JST");
            dic.Add("金沟屯", "VGP");
            dic.Add("静海", "JHP");
            dic.Add("金河", "JHX");
            dic.Add("锦河", "JHB");
            dic.Add("锦和", "JHQ");
            dic.Add("精河", "JHR");
            dic.Add("精河南", "JIR");
            dic.Add("江华", "JHZ");
            dic.Add("建湖", "AJH");
            dic.Add("纪家沟", "VJD");
            dic.Add("晋江", "JJS");
            dic.Add("江津", "JJW");
            dic.Add("姜家", "JJB");
            dic.Add("金坑", "JKT");
            dic.Add("芨岭", "JLJ");
            dic.Add("金马村", "JMM");
            dic.Add("角美", "JES");
            dic.Add("江门", "JWQ");
            dic.Add("莒南", "JOK");
            dic.Add("井南", "JNP");
            dic.Add("建瓯", "JVS");
            dic.Add("经棚", "JPC");
            dic.Add("江桥", "JQX");
            dic.Add("九三", "SSX");
            dic.Add("金山北", "EGH");
            dic.Add("京山", "JCN");
            dic.Add("建始", "JRN");
            dic.Add("嘉善", "JSH");
            dic.Add("稷山", "JVV");
            dic.Add("吉舒", "JSL");
            dic.Add("建设", "JET");
            dic.Add("甲山", "JOP");
            dic.Add("建三江", "JIB");
            dic.Add("嘉善南", "EAH");
            dic.Add("金山屯", "JTB");
            dic.Add("江所田", "JOM");
            dic.Add("景泰", "JTJ");
            dic.Add("吉文", "JWX");
            dic.Add("进贤", "JUG");
            dic.Add("莒县", "JKK");
            dic.Add("嘉祥", "JUK");
            dic.Add("介休", "JXV");
            dic.Add("井陉", "JJP");
            dic.Add("嘉兴", "JXH");
            dic.Add("嘉兴南", "EPH");
            dic.Add("夹心子", "JXT");
            dic.Add("简阳", "JYW");
            dic.Add("揭阳", "JRQ");
            dic.Add("建阳", "JYS");
            dic.Add("姜堰", "UEH");
            dic.Add("巨野", "JYK");
            dic.Add("江永", "JYZ");
            dic.Add("靖远", "JYJ");
            dic.Add("缙云", "JYH");
            dic.Add("江源", "SZL");
            dic.Add("济源", "JYF");
            dic.Add("靖远西", "JXJ");
            dic.Add("胶州北", "JZK");
            dic.Add("焦作东", "WEF");
            dic.Add("靖州", "JEQ");
            dic.Add("荆州", "JBN");
            dic.Add("金寨", "JZH");
            dic.Add("晋州", "JXP");
            dic.Add("胶州", "JXK");
            dic.Add("锦州南", "JOD");
            dic.Add("焦作", "JOF");
            dic.Add("旧庄窝", "JVP");
            dic.Add("金杖子", "JYD");
            dic.Add("富川", "FDZ");
            dic.Add("抚远", "FYB");
            dic.Add("高碑店东", "GMP");
            dic.Add("革居", "GEM");
            dic.Add("光明城", "IMQ");
            dic.Add("高邑西", "GNP");
            dic.Add("鹤壁东", "HFF");
            dic.Add("寒葱沟", "HKB");
            dic.Add("邯郸东", "HPP");
            dic.Add("合肥北城", "COH");
            dic.Add("洪河", "HPB");
            dic.Add("虎门", "IUQ");
            dic.Add("哈密南", "HLR");
            dic.Add("淮南东", "HOH");
            dic.Add("建水", "JSM");
            dic.Add("昆明", "KMM");
            dic.Add("昆明西", "KXM");
            dic.Add("拉萨", "LSO");
            dic.Add("兰州东", "LVJ");
            dic.Add("兰州", "LZJ");
            dic.Add("兰州西", "LAJ");
            dic.Add("南昌", "NCG");
            dic.Add("南京", "NJH");
            dic.Add("南京南", "NKH");
            dic.Add("南宁", "NNZ");
            dic.Add("库尔勒", "KLR");
            dic.Add("开封", "KFF");
            dic.Add("岢岚", "KLV");
            dic.Add("凯里", "KLW");
            dic.Add("喀什", "KSR");
            dic.Add("昆山南", "KNH");
            dic.Add("奎屯", "KTR");
            dic.Add("开原", "KYT");
            dic.Add("六安", "UAH");
            dic.Add("灵宝", "LBF");
            dic.Add("芦潮港", "UCH");
            dic.Add("隆昌", "LCW");
            dic.Add("陆川", "LKZ");
            dic.Add("利川", "LCN");
            dic.Add("临川", "LCG");
            dic.Add("潞城", "UTP");
            dic.Add("鹿道", "LDL");
            dic.Add("娄底", "LDQ");
            dic.Add("临汾", "LFV");
            dic.Add("良各庄", "LGP");
            dic.Add("临河", "LHC");
            dic.Add("漯河", "LON");
            dic.Add("绿化", "LWJ");
            dic.Add("隆化", "UHP");
            dic.Add("丽江", "LHM");
            dic.Add("临江", "LQL");
            dic.Add("龙井", "LJL");
            dic.Add("吕梁", "LHV");
            dic.Add("醴陵", "LLG");
            dic.Add("柳林南", "LKV");
            dic.Add("滦平", "UPP");
            dic.Add("六盘水", "UMW");
            dic.Add("灵丘", "LVV");
            dic.Add("旅顺", "LST");
            dic.Add("陇西", "LXJ");
            dic.Add("澧县", "LEQ");
            dic.Add("兰溪", "LWH");
            dic.Add("临西", "UEP");
            dic.Add("耒阳", "LYQ");
            dic.Add("洛阳", "LYF");
            dic.Add("龙岩", "LYS");
            dic.Add("洛阳东", "LDF");
            dic.Add("连云港东", "UKH");
            dic.Add("临沂", "LVK");
            dic.Add("洛阳龙门", "LLF");
            dic.Add("柳园", "DHR");
            dic.Add("凌源", "LYD");
            dic.Add("辽源", "LYL");
            dic.Add("立志", "LZX");
            dic.Add("柳州", "LZZ");
            dic.Add("辽中", "LZD");
            dic.Add("麻城", "MCN");
            dic.Add("免渡河", "MDX");
            dic.Add("牡丹江", "MDB");
            dic.Add("莫尔道嘎", "MRX");
            dic.Add("满归", "MHX");
            dic.Add("明光", "MGH");
            dic.Add("漠河", "MVX");
            dic.Add("梅江", "MKQ");
            dic.Add("茂名东", "MDQ");
            dic.Add("茂名", "MMZ");
            dic.Add("密山", "MSB");
            dic.Add("马三家", "MJT");
            dic.Add("麻尾", "VAW");
            dic.Add("绵阳", "MYW");
            dic.Add("梅州", "MOQ");
            dic.Add("满洲里", "MLX");
            dic.Add("宁波东", "NVH");
            dic.Add("南岔", "NCB");
            dic.Add("南充", "NCW");
            dic.Add("南丹", "NDZ");
            dic.Add("南大庙", "NMP");
            dic.Add("南芬", "NFT");
            dic.Add("讷河", "NHX");
            dic.Add("嫩江", "NGX");
            dic.Add("内江", "NJW");
            dic.Add("南平", "NPS");
            dic.Add("南通", "NUH");
            dic.Add("南阳", "NFF");
            dic.Add("碾子山", "NZX");
            dic.Add("开安", "KAT");
            dic.Add("库车", "KCR");
            dic.Add("康城", "KCP");
            dic.Add("库都尔", "KDX");
            dic.Add("宽甸", "KDT");
            dic.Add("克东", "KOB");
            dic.Add("开江", "KAW");
            dic.Add("康金井", "KJB");
            dic.Add("喀喇其", "KQX");
            dic.Add("开鲁", "KLC");
            dic.Add("克拉玛依", "KHR");
            dic.Add("口前", "KQL");
            dic.Add("奎山", "KAB");
            dic.Add("昆山", "KSH");
            dic.Add("克山", "KSB");
            dic.Add("开通", "KTT");
            dic.Add("康熙岭", "KXZ");
            dic.Add("克一河", "KHX");
            dic.Add("开原西", "KXT");
            dic.Add("康庄", "KZP");
            dic.Add("来宾", "UBZ");
            dic.Add("老边", "LLT");
            dic.Add("灵宝西", "LPF");
            dic.Add("龙川", "LUQ");
            dic.Add("乐昌", "LCQ");
            dic.Add("黎城", "UCP");
            dic.Add("聊城", "UCK");
            dic.Add("蓝村", "LCK");
            dic.Add("林东", "LRC");
            dic.Add("乐都", "LDO");
            dic.Add("梁底下", "LDP");
            dic.Add("六道河子", "LVP");
            dic.Add("鲁番", "LVM");
            dic.Add("廊坊", "LJP");
            dic.Add("落垡", "LOP");
            dic.Add("廊坊北", "LFP");
            dic.Add("禄丰", "LFM");
            dic.Add("老府", "UFD");
            dic.Add("兰岗", "LNB");
            dic.Add("龙骨甸", "LGM");
            dic.Add("芦沟", "LOM");
            dic.Add("龙沟", "LGJ");
            dic.Add("拉古", "LGB");
            dic.Add("临海", "UFH");
            dic.Add("林海", "LXX");
            dic.Add("拉哈", "LHX");
            dic.Add("凌海", "JID");
            dic.Add("柳河", "LNL");
            dic.Add("六合", "KLH");
            dic.Add("龙华", "LHP");
            dic.Add("滦河沿", "UNP");
            dic.Add("六合镇", "LEX");
            dic.Add("亮甲店", "LRT");
            dic.Add("刘家店", "UDT");
            dic.Add("刘家河", "LVT");
            dic.Add("连江", "LKS");
            dic.Add("李家", "LJB");
            dic.Add("罗江", "LJW");
            dic.Add("廉江", "LJZ");
            dic.Add("庐江", "UJH");
            dic.Add("两家", "UJT");
            dic.Add("龙江", "LJX");
            dic.Add("龙嘉", "UJL");
            dic.Add("莲江口", "LHB");
            dic.Add("蔺家楼", "ULK");
            dic.Add("李家坪", "LIJ");
            dic.Add("兰考", "LKF");
            dic.Add("林口", "LKB");
            dic.Add("路口铺", "LKQ");
            dic.Add("老莱", "LAX");
            dic.Add("拉林", "LAB");
            dic.Add("陆良", "LRM");
            dic.Add("龙里", "LLW");
            dic.Add("零陵", "UWZ");
            dic.Add("临澧", "LWQ");
            dic.Add("兰棱", "LLB");
            dic.Add("卢龙", "UAP");
            dic.Add("喇嘛甸", "LMX");
            dic.Add("里木店", "LMB");
            dic.Add("洛门", "LMJ");
            dic.Add("龙南", "UNG");
            dic.Add("梁平", "UQW");
            dic.Add("罗平", "LPM");
            dic.Add("落坡岭", "LPP");
            dic.Add("六盘山", "UPJ");
            dic.Add("乐平市", "LPG");
            dic.Add("临清", "UQK");
            dic.Add("龙泉寺", "UQJ");
            dic.Add("乐善村", "LUM");
            dic.Add("冷水江东", "UDQ");
            dic.Add("连山关", "LGT");
            dic.Add("流水沟", "USP");
            dic.Add("陵水", "LIQ");
            dic.Add("乐山", "UTW");
            dic.Add("罗山", "LRN");
            dic.Add("鲁山", "LAF");
            dic.Add("丽水", "USH");
            dic.Add("梁山", "LMK");
            dic.Add("灵石", "LSV");
            dic.Add("露水河", "LUL");
            dic.Add("庐山", "LSG");
            dic.Add("林盛堡", "LBT");
            dic.Add("柳树屯", "LSD");
            dic.Add("梨树镇", "LSB");
            dic.Add("龙山镇", "LAS");
            dic.Add("李石寨", "LET");
            dic.Add("黎塘", "LTZ");
            dic.Add("轮台", "LAR");
            dic.Add("芦台", "LTP");
            dic.Add("龙塘坝", "LBM");
            dic.Add("濑湍", "LVZ");
            dic.Add("骆驼巷", "LTJ");
            dic.Add("李旺", "VLJ");
            dic.Add("莱芜东", "LWK");
            dic.Add("狼尾山", "LRJ");
            dic.Add("灵武", "LNJ");
            dic.Add("莱芜西", "UXK");
            dic.Add("朗乡", "LXB");
            dic.Add("陇县", "LXY");
            dic.Add("临湘", "LXQ");
            dic.Add("莱西", "LXK");
            dic.Add("林西", "LXC");
            dic.Add("滦县", "UXP");
            dic.Add("略阳", "LYY");
            dic.Add("莱阳", "LYK");
            dic.Add("辽阳", "LYT");
            dic.Add("临沂北", "UYK");
            dic.Add("凌源东", "LDD");
            dic.Add("连云港", "UIH");
            dic.Add("老羊壕", "LYC");
            dic.Add("临颍", "LNF");
            dic.Add("老营", "LXL");
            dic.Add("龙游", "LMH");
            dic.Add("罗源", "LVS");
            dic.Add("林源", "LYX");
            dic.Add("涟源", "LAQ");
            dic.Add("涞源", "LYP");
            dic.Add("耒阳西", "LPQ");
            dic.Add("临泽", "LEJ");
            dic.Add("龙爪沟", "LZT");
            dic.Add("雷州", "UAQ");
            dic.Add("六枝", "LIW");
            dic.Add("鹿寨", "LIZ");
            dic.Add("来舟", "LZS");
            dic.Add("龙镇", "LZA");
            dic.Add("拉鲊", "LEM");
            dic.Add("明安", "MAC");
            dic.Add("马鞍山", "MAH");
            dic.Add("毛坝", "MBY");
            dic.Add("毛坝关", "MGY");
            dic.Add("麻城北", "MBN");
            dic.Add("渑池", "MCF");
            dic.Add("明城", "MCL");
            dic.Add("庙城", "MAP");
            dic.Add("渑池南", "MNF");
            dic.Add("茅草坪", "KPM");
            dic.Add("猛洞河", "MUQ");
            dic.Add("磨刀石", "MOB");
            dic.Add("弥渡", "MDF");
            dic.Add("帽儿山", "MRB");
            dic.Add("明港", "MGN");
            dic.Add("梅河口", "MHL");
            dic.Add("马皇", "MHZ");
            dic.Add("孟家岗", "MGB");
            dic.Add("美兰", "MHQ");
            dic.Add("汨罗东", "MQQ");
            dic.Add("马莲河", "MHB");
            dic.Add("茅岭", "MLZ");
            dic.Add("庙岭", "MLL");
            dic.Add("茂林", "MLD");
            dic.Add("穆棱", "MLB");
            dic.Add("马林", "MID");
            dic.Add("马龙", "MGM");
            dic.Add("汨罗", "MLQ");
            dic.Add("木里图", "MUD");
            dic.Add("密马龙", "MMM");
            dic.Add("玛纳斯湖", "MNR");
            dic.Add("冕宁", "UGW");
            dic.Add("沐滂", "MPQ");
            dic.Add("马桥河", "MQB");
            dic.Add("闽清", "MQS");
            dic.Add("民权", "MQF");
            dic.Add("明水河", "MUT");
            dic.Add("麻山", "MAB");
            dic.Add("眉山", "MSW");
            dic.Add("漫水湾", "MKW");
            dic.Add("茂舍祖", "MOM");
            dic.Add("米沙子", "MST");
            dic.Add("庙台子", "MZB");
            dic.Add("美溪", "MEB");
            dic.Add("勉县", "MVY");
            dic.Add("麻阳", "MVQ");
            dic.Add("牧羊村", "MCM");
            dic.Add("米易", "MMW");
            dic.Add("麦园", "MYS");
            dic.Add("墨玉", "MUR");
            dic.Add("密云", "MUP");
            dic.Add("庙庄", "MZJ");
            dic.Add("米脂", "MEY");
            dic.Add("明珠", "MFQ");
            dic.Add("宁安", "NAB");
            dic.Add("农安", "NAT");
            dic.Add("南博山", "NBK");
            dic.Add("南仇", "NCK");
            dic.Add("南城司", "NSP");
            dic.Add("宁村", "NCZ");
            dic.Add("宁德", "NES");
            dic.Add("南观村", "NGP");
            dic.Add("南宫东", "NFP");
            dic.Add("南关岭", "NLT");
            dic.Add("宁国", "NNH");
            dic.Add("宁海", "NHH");
            dic.Add("南河川", "NHJ");
            dic.Add("南华", "NHS");
            dic.Add("泥河子", "NHD");
            dic.Add("宁家", "NVT");
            dic.Add("牛家", "NJB");
            dic.Add("南靖", "NJS");
            dic.Add("能家", "NJD");
            dic.Add("南口", "NKP");
            dic.Add("南口前", "NKT");
            dic.Add("南朗", "NNQ");
            dic.Add("乃林", "NLD");
            dic.Add("尼勒克", "NIR");
            dic.Add("那罗", "ULZ");
            dic.Add("宁陵县", "NLF");
            dic.Add("奈曼", "NMD");
            dic.Add("宁明", "NMZ");
            dic.Add("南木", "NMX");
            dic.Add("南平南", "NNS");
            dic.Add("那铺", "NPZ");
            dic.Add("南桥", "NQD");
            dic.Add("那曲", "NQO");
            dic.Add("暖泉", "NQJ");
            dic.Add("南台", "NTT");
            dic.Add("南头", "NOQ");
            dic.Add("宁武", "NWV");
            dic.Add("南湾子", "NWP");
            dic.Add("南翔北", "NEH");
            dic.Add("宁乡", "NXQ");
            dic.Add("内乡", "NXF");
            dic.Add("牛心台", "NXT");
            dic.Add("南峪", "NUP");
            dic.Add("娘子关", "NIP");
            dic.Add("南召", "NAF");
            dic.Add("南杂木", "NZT");
            dic.Add("库伦", "KLD");
            dic.Add("漯河西", "LBN");
            dic.Add("明港东", "MDN");
            dic.Add("蒙自北", "MBM");
            dic.Add("上海", "SHH");
            dic.Add("上海南", "SNH");
            dic.Add("上海虹桥", "AOH");
            dic.Add("上海西", "SXH");
            dic.Add("天津北", "TBP");
            dic.Add("天津", "TJP");
            dic.Add("天津南", "TIP");
            dic.Add("天津西", "TXP");
            dic.Add("石家庄北", "VVP");
            dic.Add("石家庄", "SJP");
            dic.Add("沈阳", "SYT");
            dic.Add("沈阳北", "SBT");
            dic.Add("沈阳东", "SDT");
            dic.Add("太原北", "TBV");
            dic.Add("太原东", "TDV");
            dic.Add("太原", "TYV");
            dic.Add("平顶山", "PEN");
            dic.Add("盘锦", "PVD");
            dic.Add("平凉", "PIJ");
            dic.Add("平凉南", "POJ");
            dic.Add("平泉", "PQP");
            dic.Add("坪石", "PSQ");
            dic.Add("萍乡", "PXG");
            dic.Add("凭祥", "PXZ");
            dic.Add("郫县西", "PCW");
            dic.Add("攀枝花", "PRW");
            dic.Add("蕲春", "QRN");
            dic.Add("青城山", "QSW");
            dic.Add("青岛", "QDK");
            dic.Add("清河城", "QYP");
            dic.Add("黔江", "QNW");
            dic.Add("曲靖", "QJM");
            dic.Add("前进镇", "QEB");
            dic.Add("齐齐哈尔", "QHX");
            dic.Add("七台河", "QTB");
            dic.Add("沁县", "QVV");
            dic.Add("泉州东", "QRS");
            dic.Add("泉州", "QYS");
            dic.Add("衢州", "QEH");
            dic.Add("融安", "RAZ");
            dic.Add("汝箕沟", "RQJ");
            dic.Add("瑞金", "RJG");
            dic.Add("日照", "RZK");
            dic.Add("双城堡", "SCB");
            dic.Add("绥芬河", "SFB");
            dic.Add("韶关东", "SGQ");
            dic.Add("山海关", "SHD");
            dic.Add("绥化", "SHB");
            dic.Add("三间房", "SFX");
            dic.Add("苏家屯", "SXT");
            dic.Add("舒兰", "SLL");
            dic.Add("三明", "SMS");
            dic.Add("神木", "OMY");
            dic.Add("三门峡", "SMF");
            dic.Add("商南", "ONY");
            dic.Add("遂宁", "NIW");
            dic.Add("四平", "SPT");
            dic.Add("商丘", "SQF");
            dic.Add("上饶", "SRG");
            dic.Add("韶山", "SSQ");
            dic.Add("宿松", "OAH");
            dic.Add("汕头", "OTQ");
            dic.Add("邵武", "SWS");
            dic.Add("涉县", "OEP");
            dic.Add("三亚", "SEQ");
            dic.Add("邵阳", "SYQ");
            dic.Add("十堰", "SNN");
            dic.Add("双鸭山", "SSB");
            dic.Add("松原", "VYT");
            dic.Add("深圳", "SZQ");
            dic.Add("苏州", "SZH");
            dic.Add("随州", "SZN");
            dic.Add("宿州", "OXH");
            dic.Add("朔州", "SUV");
            dic.Add("深圳西", "OSQ");
            dic.Add("塘豹", "TBQ");
            dic.Add("塔尔气", "TVX");
            dic.Add("潼关", "TGY");
            dic.Add("塘沽", "TGP");
            dic.Add("塔河", "TXX");
            dic.Add("通化", "THL");
            dic.Add("泰来", "TLX");
            dic.Add("吐鲁番", "TFR");
            dic.Add("通辽", "TLD");
            dic.Add("铁岭", "TLT");
            dic.Add("陶赖昭", "TPT");
            dic.Add("图们", "TML");
            dic.Add("铜仁", "RDQ");
            dic.Add("唐山北", "FUP");
            dic.Add("田师府", "TFT");
            dic.Add("泰山", "TAK");
            dic.Add("天水", "TSJ");
            dic.Add("唐山", "TSP");
            dic.Add("通远堡", "TYT");
            dic.Add("太阳升", "TQT");
            dic.Add("泰州", "UTH");
            dic.Add("桐梓", "TZW");
            dic.Add("通州西", "TAP");
            dic.Add("平安", "PAL");
            dic.Add("蓬安", "PAW");
            dic.Add("平安驿", "PNO");
            dic.Add("磐安镇", "PAJ");
            dic.Add("平安镇", "PZT");
            dic.Add("蒲城东", "PEY");
            dic.Add("蒲城", "PCY");
            dic.Add("裴德", "PDB");
            dic.Add("偏店", "PRP");
            dic.Add("平顶山西", "BFF");
            dic.Add("坡底下", "PXJ");
            dic.Add("瓢儿屯", "PRT");
            dic.Add("平房", "PFB");
            dic.Add("平岗", "PGL");
            dic.Add("平关", "PGM");
            dic.Add("盘关", "PAM");
            dic.Add("平果", "PGZ");
            dic.Add("徘徊北", "PHP");
            dic.Add("平河口", "PHM");
            dic.Add("盘锦北", "PBD");
            dic.Add("潘家店", "PDP");
            dic.Add("皮口", "PKT");
            dic.Add("普兰店", "PLT");
            dic.Add("偏岭", "PNT");
            dic.Add("平山", "PSB");
            dic.Add("彭山", "PSW");
            dic.Add("皮山", "PSR");
            dic.Add("彭水", "PHW");
            dic.Add("磐石", "PSL");
            dic.Add("平社", "PSV");
            dic.Add("平台", "PVT");
            dic.Add("平田", "PTM");
            dic.Add("莆田", "PTS");
            dic.Add("葡萄菁", "PTW");
            dic.Add("普湾", "PWT");
            dic.Add("平旺", "PWV");
            dic.Add("平型关", "PGV");
            dic.Add("普雄", "POW");
            dic.Add("平洋", "PYX");
            dic.Add("彭阳", "PYJ");
            dic.Add("平遥", "PYV");
            dic.Add("平邑", "PIK");
            dic.Add("平原堡", "PPJ");
            dic.Add("平原", "PYK");
            dic.Add("平峪", "PYP");
            dic.Add("彭泽", "PZG");
            dic.Add("邳州", "PJH");
            dic.Add("平庄", "PZD");
            dic.Add("泡子", "POD");
            dic.Add("平庄南", "PND");
            dic.Add("乾安", "QOT");
            dic.Add("庆安", "QAB");
            dic.Add("迁安", "QQP");
            dic.Add("祁东北", "QRQ");
            dic.Add("七甸", "QDM");
            dic.Add("曲阜东", "QAK");
            dic.Add("庆丰", "QFT");
            dic.Add("奇峰塔", "QVP");
            dic.Add("曲阜", "QFK");
            dic.Add("勤丰营", "QFM");
            dic.Add("琼海", "QYQ");
            dic.Add("秦皇岛", "QTP");
            dic.Add("千河", "QUY");
            dic.Add("清河", "QIP");
            dic.Add("清河门", "QHD");
            dic.Add("清华园", "QHP");
            dic.Add("渠旧", "QJZ");
            dic.Add("綦江", "QJW");
            dic.Add("潜江", "QJN");
            dic.Add("全椒", "INH");
            dic.Add("秦家", "QJB");
            dic.Add("祁家堡", "QBT");
            dic.Add("清涧县", "QNY");
            dic.Add("秦家庄", "QZV");
            dic.Add("七里河", "QLD");
            dic.Add("渠黎", "QLZ");
            dic.Add("秦岭", "QLY");
            dic.Add("青龙山", "QGH");
            dic.Add("青龙寺", "QSM");
            dic.Add("祁门", "QIH");
            dic.Add("前磨头", "QMP");
            dic.Add("青山", "QSB");
            dic.Add("全胜", "QVB");
            dic.Add("确山", "QSN");
            dic.Add("清水", "QUJ");
            dic.Add("前山", "QXQ");
            dic.Add("戚墅堰", "QYH");
            dic.Add("青田", "QVH");
            dic.Add("桥头", "QAT");
            dic.Add("青铜峡", "QTJ");
            dic.Add("前卫", "QWD");
            dic.Add("前苇塘", "QWP");
            dic.Add("渠县", "QRW");
            dic.Add("祁县", "QXV");
            dic.Add("青县", "QXP");
            dic.Add("桥西", "QXJ");
            dic.Add("清徐", "QUV");
            dic.Add("旗下营", "QXC");
            dic.Add("千阳", "QOY");
            dic.Add("沁阳", "QYF");
            dic.Add("泉阳", "QYL");
            dic.Add("祁阳北", "QVQ");
            dic.Add("七营", "QYJ");
            dic.Add("庆阳山", "QSJ");
            dic.Add("清远", "QBQ");
            dic.Add("清原", "QYT");
            dic.Add("钦州东", "QDZ");
            dic.Add("全州", "QZZ");
            dic.Add("钦州", "QRZ");
            dic.Add("青州市", "QZK");
            dic.Add("瑞安", "RAH");
            dic.Add("荣昌", "RCW");
            dic.Add("瑞昌", "RCG");
            dic.Add("如皋", "RBH");
            dic.Add("容桂", "RUQ");
            dic.Add("任丘", "RQP");
            dic.Add("乳山", "ROK");
            dic.Add("融水", "RSZ");
            dic.Add("热水", "RSD");
            dic.Add("容县", "RXZ");
            dic.Add("饶阳", "RVP");
            dic.Add("汝阳", "RYF");
            dic.Add("绕阳河", "RHD");
            dic.Add("汝州", "ROF");
            dic.Add("石坝", "OBJ");
            dic.Add("上板城", "SBP");
            dic.Add("施秉", "AQW");
            dic.Add("上板城南", "OBP");
            dic.Add("世博园", "ZWT");
            dic.Add("双城北", "SBB");
            dic.Add("商城", "SWN");
            dic.Add("莎车", "SCR");
            dic.Add("顺昌", "SCS");
            dic.Add("舒城", "OCH");
            dic.Add("神池", "SMV");
            dic.Add("沙城", "SCP");
            dic.Add("石城", "SCT");
            dic.Add("山城镇", "SCL");
            dic.Add("山丹", "SDJ");
            dic.Add("顺德", "ORQ");
            dic.Add("绥德", "ODY");
            dic.Add("邵东", "SOQ");
            dic.Add("水洞", "SIL");
            dic.Add("商都", "SXC");
            dic.Add("十渡", "SEP");
            dic.Add("四道湾", "OUD");
            dic.Add("顺德学院", "OJQ");
            dic.Add("绅坊", "OLH");
            dic.Add("双丰", "OFB");
            dic.Add("四方台", "STB");
            dic.Add("水富", "OTW");
            dic.Add("三关口", "OKJ");
            dic.Add("桑根达来", "OGC");
            dic.Add("韶关", "SNQ");
            dic.Add("上高镇", "SVK");
            dic.Add("上杭", "JBS");
            dic.Add("沙海", "SED");
            dic.Add("松河", "SBM");
            dic.Add("沙河", "SHP");
            dic.Add("沙河口", "SKT");
            dic.Add("赛汗塔拉", "SHC");
            dic.Add("沙河市", "VOP");
            dic.Add("沙后所", "SSD");
            dic.Add("山河屯", "SHL");
            dic.Add("三河县", "OXP");
            dic.Add("四合永", "OHD");
            dic.Add("三汇镇", "OZW");
            dic.Add("双河镇", "SEL");
            dic.Add("石河子", "SZR");
            dic.Add("三合庄", "SVP");
            dic.Add("三家店", "ODP");
            dic.Add("水家湖", "SQH");
            dic.Add("沈家河", "OJJ");
            dic.Add("松江河", "SJL");
            dic.Add("尚家", "SJB");
            dic.Add("孙家", "SUB");
            dic.Add("沈家", "OJB");
            dic.Add("松江", "SAH");
            dic.Add("三江口", "SKD");
            dic.Add("司家岭", "OLK");
            dic.Add("松江南", "IMH");
            dic.Add("石景山南", "SRP");
            dic.Add("邵家堂", "SJJ");
            dic.Add("三江县", "SOZ");
            dic.Add("三家寨", "SMM");
            dic.Add("十家子", "SJD");
            dic.Add("松江镇", "OZL");
            dic.Add("施家嘴", "SHM");
            dic.Add("深井子", "SWT");
            dic.Add("什里店", "OMP");
            dic.Add("疏勒", "SUR");
            dic.Add("疏勒河", "SHJ");
            dic.Add("舍力虎", "VLD");
            dic.Add("石磷", "SPB");
            dic.Add("绥棱", "SIB");
            dic.Add("石岭", "SOL");
            dic.Add("石林", "SLM");
            dic.Add("石林南", "LNM");
            dic.Add("石龙", "SLQ");
            dic.Add("萨拉齐", "SLC");
            dic.Add("索伦", "SNT");
            dic.Add("商洛", "OLY");
            dic.Add("沙岭子", "SLP");
            dic.Add("三门峡南", "SCF");
            dic.Add("三门县", "OQH");
            dic.Add("石门县", "OMQ");
            dic.Add("三门峡西", "SXF");
            dic.Add("肃宁", "SYP");
            dic.Add("宋", "SOB");
            dic.Add("双牌", "SBZ");
            dic.Add("四平东", "PPT");
            dic.Add("遂平", "SON");
            dic.Add("沙坡头", "SFJ");
            dic.Add("商丘南", "SPF");
            dic.Add("水泉", "SID");
            dic.Add("石泉县", "SXY");
            dic.Add("石桥子", "SQT");
            dic.Add("石人城", "SRB");
            dic.Add("石人", "SRL");
            dic.Add("山市", "SQB");
            dic.Add("神树", "SWB");
            dic.Add("鄯善", "SSR");
            dic.Add("三水", "SJQ");
            dic.Add("泗水", "OSK");
            dic.Add("石山", "SAD");
            dic.Add("松树", "SFT");
            dic.Add("首山", "SAT");
            dic.Add("三十家", "SRD");
            dic.Add("三十里堡", "SST");
            dic.Add("松树镇", "SSL");
            dic.Add("松桃", "MZQ");
            dic.Add("索图罕", "SHX");
            dic.Add("三堂集", "SDH");
            dic.Add("石头", "OTB");
            dic.Add("神头", "SEV");
            dic.Add("沙沱", "SFM");
            dic.Add("上万", "SWP");
            dic.Add("孙吴", "SKB");
            dic.Add("沙湾县", "SXR");
            dic.Add("遂溪", "SXZ");
            dic.Add("沙县", "SAS");
            dic.Add("绍兴", "SOH");
            dic.Add("歙县", "OVH");
            dic.Add("石岘", "SXL");
            dic.Add("上西铺", "SXM");
            dic.Add("石峡子", "SXJ");
            dic.Add("绥阳", "SYB");
            dic.Add("沭阳", "FMH");
            dic.Add("寿阳", "SYV");
            dic.Add("水洋", "OYP");
            dic.Add("三阳川", "SYJ");
            dic.Add("上腰墩", "SPJ");
            dic.Add("三营", "OEJ");
            dic.Add("顺义", "SOP");
            dic.Add("三义井", "OYD");
            dic.Add("三源浦", "SYL");
            dic.Add("三原", "SAY");
            dic.Add("上虞", "BDH");
            dic.Add("上园", "SUD");
            dic.Add("水源", "OYJ");
            dic.Add("桑园子", "SAJ");
            dic.Add("绥中北", "SND");
            dic.Add("苏州北", "OHH");
            dic.Add("宿州东", "SRH");
            dic.Add("深圳东", "BJQ");
            dic.Add("深州", "OZP");
            dic.Add("孙镇", "OZY");
            dic.Add("绥中", "SZD");
            dic.Add("尚志", "SZB");
            dic.Add("师庄", "SNM");
            dic.Add("松滋", "SIN");
            dic.Add("师宗", "SEM");
            dic.Add("苏州园区", "KAH");
            dic.Add("苏州新区", "ITH");
            dic.Add("石嘴山", "SZJ");
            dic.Add("泰安", "TMK");
            dic.Add("台安", "TID");
            dic.Add("通安驿", "TAJ");
            dic.Add("桐柏", "TBF");
            dic.Add("通北", "TBB");
            dic.Add("汤池", "TCX");
            dic.Add("桐城", "TTH");
            dic.Add("郯城", "TZK");
            dic.Add("铁厂", "TCL");
            dic.Add("桃村", "TCK");
            dic.Add("通道", "TRQ");
            dic.Add("田东", "TDZ");
            dic.Add("天岗", "TGL");
            dic.Add("土贵乌拉", "TGC");
            dic.Add("通沟", "TOL");
            dic.Add("太谷", "TGV");
            dic.Add("塔哈", "THX");
            dic.Add("棠海", "THM");
            dic.Add("唐河", "THF");
            dic.Add("泰和", "THG");
            dic.Add("太湖", "TKH");
            dic.Add("团结", "TIX");
            dic.Add("谭家井", "TNJ");
            dic.Add("陶家屯", "TOT");
            dic.Add("唐家湾", "PDQ");
            dic.Add("统军庄", "TZP");
            dic.Add("泰康", "TKX");
            dic.Add("吐列毛杜", "TMD");
            dic.Add("图里河", "TEX");
            dic.Add("亭亮", "TIZ");
            dic.Add("田林", "TFZ");
            dic.Add("铜陵", "TJH");
            dic.Add("铁力", "TLB");
            dic.Add("铁岭西", "PXT");
            dic.Add("天门", "TMN");
            dic.Add("天门南", "TNN");
            dic.Add("太姥山", "TLS");
            dic.Add("土牧尔台", "TRC");
            dic.Add("土门子", "TCJ");
            dic.Add("潼南", "TVW");
            dic.Add("洮南", "TVT");
            dic.Add("太平川", "TIT");
            dic.Add("太平镇", "TEB");
            dic.Add("图强", "TQX");
            dic.Add("台前", "TTK");
            dic.Add("天桥岭", "TQL");
            dic.Add("土桥子", "TQJ");
            dic.Add("汤山城", "TCT");
            dic.Add("桃山", "TAB");
            dic.Add("塔石嘴", "TIM");
            dic.Add("通途", "TUT");
            dic.Add("汤旺河", "THB");
            dic.Add("同心", "TXJ");
            dic.Add("土溪", "TSW");
            dic.Add("桐乡", "TCH");
            dic.Add("田阳", "TRZ");
            dic.Add("桃映", "TKQ");
            dic.Add("天义", "TND");
            dic.Add("汤阴", "TYF");
            dic.Add("驼腰岭", "TIL");
            dic.Add("太阳山", "TYJ");
            dic.Add("汤原", "TYB");
            dic.Add("塔崖驿", "TYP");
            dic.Add("滕州东", "TEK");
            dic.Add("台州", "TZH");
            dic.Add("天祝", "TZJ");
            dic.Add("滕州", "TXK");
            dic.Add("天镇", "TZV");
            dic.Add("桐子林", "TEW");
            dic.Add("天柱山", "QWH");
            dic.Add("前锋", "QFB");
            dic.Add("庆盛", "QSQ");
            dic.Add("深圳北", "IOQ");
            dic.Add("通海", "TAM");
            dic.Add("武汉", "WHN");
            dic.Add("王家营西", "KNM");
            dic.Add("乌鲁木齐", "WMR");
            dic.Add("西安北", "EAY");
            dic.Add("西安", "XAY");
            dic.Add("西安南", "CAY");
            dic.Add("西宁西", "XXO");
            dic.Add("银川", "YIJ");
            dic.Add("郑州", "ZZF");
            dic.Add("五常", "WCB");
            dic.Add("武昌", "WCN");
            dic.Add("瓦房店", "WDT");
            dic.Add("威海", "WKK");
            dic.Add("芜湖", "WHH");
            dic.Add("乌海西", "WXC");
            dic.Add("吴家屯", "WJT");
            dic.Add("武隆", "WLW");
            dic.Add("乌兰浩特", "WWT");
            dic.Add("渭南", "WNY");
            dic.Add("威舍", "WSM");
            dic.Add("歪头山", "WIT");
            dic.Add("武威", "WUJ");
            dic.Add("武威南", "WWJ");
            dic.Add("无锡", "WXH");
            dic.Add("乌西", "WXR");
            dic.Add("乌伊岭", "WPB");
            dic.Add("武夷山", "WAS");
            dic.Add("万源", "WYY");
            dic.Add("万州", "WYW");
            dic.Add("梧州", "WZZ");
            dic.Add("温州", "RZH");
            dic.Add("温州南", "VRH");
            dic.Add("西昌", "ECW");
            dic.Add("许昌", "XCF");
            dic.Add("西昌南", "ENW");
            dic.Add("香坊", "XFB");
            dic.Add("轩岗", "XGV");
            dic.Add("兴国", "EUG");
            dic.Add("宣汉", "XHY");
            dic.Add("新会", "EFQ");
            dic.Add("新晃", "XLQ");
            dic.Add("锡林浩特", "XTC");
            dic.Add("兴隆县", "EXP");
            dic.Add("厦门北", "XKS");
            dic.Add("厦门", "XMS");
            dic.Add("厦门高崎", "XBS");
            dic.Add("秀山", "ETW");
            dic.Add("小市", "XST");
            dic.Add("向塘", "XTG");
            dic.Add("宣威", "XWM");
            dic.Add("新乡", "XXF");
            dic.Add("信阳", "XUN");
            dic.Add("咸阳", "XYY");
            dic.Add("襄阳", "XFN");
            dic.Add("熊岳城", "XYT");
            dic.Add("兴义", "XRZ");
            dic.Add("新沂", "VIH");
            dic.Add("新余", "XUG");
            dic.Add("徐州", "XCH");
            dic.Add("延安", "YWY");
            dic.Add("宜宾", "YBW");
            dic.Add("亚布力南", "YWB");
            dic.Add("叶柏寿", "YBD");
            dic.Add("宜昌东", "HAN");
            dic.Add("永川", "YCW");
            dic.Add("宜春", "YCG");
            dic.Add("宜昌", "YCN");
            dic.Add("盐城", "AFH");
            dic.Add("运城", "YNV");
            dic.Add("伊春", "YCB");
            dic.Add("榆次", "YCV");
            dic.Add("杨村", "YBP");
            dic.Add("伊尔施", "YET");
            dic.Add("燕岗", "YGW");
            dic.Add("永济", "YIV");
            dic.Add("延吉", "YJL");
            dic.Add("营口", "YKT");
            dic.Add("牙克石", "YKX");
            dic.Add("阎良", "YNY");
            dic.Add("玉林", "YLZ");
            dic.Add("榆林", "ALY");
            dic.Add("一面坡", "YPB");
            dic.Add("伊宁", "YMR");
            dic.Add("阳平关", "YAY");
            dic.Add("玉屏", "YZW");
            dic.Add("原平", "YPV");
            dic.Add("延庆", "YNP");
            dic.Add("阳泉曲", "YYV");
            dic.Add("玉泉", "YQB");
            dic.Add("阳泉", "AQP");
            dic.Add("玉山", "YNG");
            dic.Add("营山", "NUW");
            dic.Add("燕山", "AOP");
            dic.Add("榆树", "YRT");
            dic.Add("鹰潭", "YTG");
            dic.Add("烟台", "YAK");
            dic.Add("伊图里河", "YEX");
            dic.Add("玉田县", "ATP");
            dic.Add("义乌", "YWH");
            dic.Add("阳新", "YON");
            dic.Add("义县", "YXD");
            dic.Add("益阳", "AEQ");
            dic.Add("岳阳", "YYQ");
            dic.Add("永州", "AOQ");
            dic.Add("扬州", "YLH");
            dic.Add("淄博", "ZBK");
            dic.Add("镇城底", "ZDV");
            dic.Add("自贡", "ZGW");
            dic.Add("珠海", "ZHQ");
            dic.Add("珠海北", "ZIQ");
            dic.Add("湛江", "ZJZ");
            dic.Add("镇江", "ZJH");
            dic.Add("张家界", "DIQ");
            dic.Add("张家口", "ZKP");
            dic.Add("张家口南", "ZMP");
            dic.Add("周口", "ZKN");
            dic.Add("哲里木", "ZLC");
            dic.Add("扎兰屯", "ZTX");
            dic.Add("驻马店", "ZDN");
            dic.Add("肇庆", "ZVQ");
            dic.Add("周水子", "ZIT");
            dic.Add("昭通", "ZDW");
            dic.Add("中卫", "ZWJ");
            dic.Add("资阳", "ZYW");
            dic.Add("遵义", "ZIW");
            dic.Add("枣庄", "ZEK");
            dic.Add("资中", "ZZW");
            dic.Add("株洲", "ZZQ");
            dic.Add("枣庄西", "ZFK");
            dic.Add("文安", "WBP");
            dic.Add("武安", "WAP");
            dic.Add("王安镇", "WVP");
            dic.Add("旺苍", "WEW");
            dic.Add("五叉沟", "WCT");
            dic.Add("文昌", "WEQ");
            dic.Add("温春", "WDB");
            dic.Add("五大连池", "WRB");
            dic.Add("文登", "WBK");
            dic.Add("五道沟", "WDL");
            dic.Add("五道河", "WHP");
            dic.Add("文地", "WNZ");
            dic.Add("卫东", "WVT");
            dic.Add("武当山", "WRN");
            dic.Add("望都", "WDP");
            dic.Add("乌尔旗汗", "WHX");
            dic.Add("潍坊", "WFK");
            dic.Add("万发屯", "WFB");
            dic.Add("王府", "WUT");
            dic.Add("瓦房店西", "WXT");
            dic.Add("王岗", "WGB");
            dic.Add("武功", "WGY");
            dic.Add("湾沟", "WGL");
            dic.Add("吴官田", "WGM");
            dic.Add("乌海", "WVC");
            dic.Add("苇河", "WHB");
            dic.Add("卫辉", "WHF");
            dic.Add("吴家川", "WCJ");
            dic.Add("五家", "WUB");
            dic.Add("威箐", "WAM");
            dic.Add("午汲", "WJP");
            dic.Add("渭津", "WJL");
            dic.Add("王家湾", "WJJ");
            dic.Add("倭肯", "WQB");
            dic.Add("五棵树", "WKT");
            dic.Add("五龙背", "WBT");
            dic.Add("乌兰哈达", "WLC");
            dic.Add("万乐", "WEB");
            dic.Add("瓦拉干", "WVX");
            dic.Add("温岭", "VHH");
            dic.Add("五莲", "WLK");
            dic.Add("乌拉特前旗", "WQC");
            dic.Add("乌拉山", "WSC");
            dic.Add("卧里屯", "WLX");
            dic.Add("渭南北", "WBY");
            dic.Add("乌奴耳", "WRX");
            dic.Add("万宁", "WNQ");
            dic.Add("万年", "WWG");
            dic.Add("渭南南", "WVY");
            dic.Add("渭南镇", "WNJ");
            dic.Add("沃皮", "WPT");
            dic.Add("吴堡", "WUY");
            dic.Add("吴桥", "WUP");
            dic.Add("汪清", "WQL");
            dic.Add("武清", "WWP");
            dic.Add("温泉", "WQM");
            dic.Add("武山", "WSJ");
            dic.Add("文水", "WEV");
            dic.Add("魏善庄", "WSP");
            dic.Add("王瞳", "WTP");
            dic.Add("五台山", "WSV");
            dic.Add("王团庄", "WZJ");
            dic.Add("五五", "WVR");
            dic.Add("无锡东", "WGH");
            dic.Add("卫星", "WVB");
            dic.Add("闻喜", "WXV");
            dic.Add("武乡", "WVV");
            dic.Add("无锡新区", "IFH");
            dic.Add("武穴", "WXN");
            dic.Add("吴圩", "WYZ");
            dic.Add("王杨", "WYB");
            dic.Add("五营", "WWB");
            dic.Add("武义", "RYH");
            dic.Add("瓦窑田", "WIM");
            dic.Add("五原", "WYC");
            dic.Add("苇子沟", "WZL");
            dic.Add("韦庄", "WZY");
            dic.Add("五寨", "WZV");
            dic.Add("王兆屯", "WZB");
            dic.Add("微子镇", "WQP");
            dic.Add("魏杖子", "WKD");
            dic.Add("新安", "EAM");
            dic.Add("兴安", "XAZ");
            dic.Add("新安县", "XAF");
            dic.Add("新保安", "XAP");
            dic.Add("下板城", "EBP");
            dic.Add("西八里", "XLP");
            dic.Add("宣城", "ECH");
            dic.Add("兴城", "XCD");
            dic.Add("小村", "XEM");
            dic.Add("新绰源", "XRX");
            dic.Add("下城子", "XCB");
            dic.Add("新城子", "XCT");
            dic.Add("喜德", "EDW");
            dic.Add("小得江", "EJM");
            dic.Add("西大庙", "XMP");
            dic.Add("小董", "XEZ");
            dic.Add("小东", "XOD");
            dic.Add("西斗铺", "XPC");
            dic.Add("息烽", "XFW");
            dic.Add("信丰", "EFG");
            dic.Add("襄汾", "XFV");
            dic.Add("新干", "EGG");
            dic.Add("孝感", "XGN");
            dic.Add("西固城", "XUJ");
            dic.Add("夏官营", "XGJ");
            dic.Add("西岗子", "NBB");
            dic.Add("襄河", "XXB");
            dic.Add("新和", "XIR");
            dic.Add("宣和", "XWJ");
            dic.Add("斜河涧", "EEP");
            dic.Add("新华屯", "XAX");
            dic.Add("新华", "XHB");
            dic.Add("新化", "EHQ");
            dic.Add("宣化", "XHP");
            dic.Add("兴和西", "XEC");
            dic.Add("小河沿", "XYD");
            dic.Add("下花园", "XYP");
            dic.Add("小河镇", "EKY");
            dic.Add("徐家", "XJB");
            dic.Add("峡江", "EJG");
            dic.Add("新绛", "XJV");
            dic.Add("辛集", "ENP");
            dic.Add("新江", "XJM");
            dic.Add("西街口", "EKM");
            dic.Add("许家屯", "XJT");
            dic.Add("许家台", "XTJ");
            dic.Add("谢家镇", "XMT");
            dic.Add("兴凯", "EKB");
            dic.Add("小榄", "EAQ");
            dic.Add("香兰", "XNB");
            dic.Add("兴隆店", "XDD");
            dic.Add("新乐", "ELP");
            dic.Add("新林", "XPX");
            dic.Add("小岭", "XLB");
            dic.Add("新李", "XLJ");
            dic.Add("西林", "XYB");
            dic.Add("西柳", "GCT");
            dic.Add("仙林", "XPH");
            dic.Add("新立屯", "XLD");
            dic.Add("小路溪", "XLM");
            dic.Add("兴隆镇", "XZB");
            dic.Add("新立镇", "XGT");
            dic.Add("新民", "XMD");
            dic.Add("西麻山", "XMB");
            dic.Add("下马塘", "XAT");
            dic.Add("孝南", "XNV");
            dic.Add("咸宁北", "XRN");
            dic.Add("兴宁", "ENQ");
            dic.Add("咸宁", "XNN");
            dic.Add("西平", "XPN");
            dic.Add("兴平", "XPY");
            dic.Add("新坪田", "XPM");
            dic.Add("霞浦", "XOS");
            dic.Add("溆浦", "EPQ");
            dic.Add("犀浦", "XIW");
            dic.Add("新青", "XQB");
            dic.Add("新邱", "XQD");
            dic.Add("兴泉堡", "XQJ");
            dic.Add("仙人桥", "XRL");
            dic.Add("小寺沟", "ESP");
            dic.Add("杏树", "XSB");
            dic.Add("夏石", "XIZ");
            dic.Add("浠水", "XZN");
            dic.Add("下社", "XSV");
            dic.Add("徐水", "XSP");
            dic.Add("小哨", "XAM");
            dic.Add("新松浦", "XOB");
            dic.Add("杏树屯", "XDT");
            dic.Add("许三湾", "XSJ");
            dic.Add("湘潭", "XTQ");
            dic.Add("邢台", "XTP");
            dic.Add("仙桃西", "XAN");
            dic.Add("下台子", "EIP");
            dic.Add("徐闻", "XJQ");
            dic.Add("新窝铺", "EPD");
            dic.Add("修武", "XWF");
            dic.Add("新县", "XSN");
            dic.Add("息县", "ENN");
            dic.Add("西乡", "XQY");
            dic.Add("湘乡", "XXQ");
            dic.Add("西峡", "XIF");
            dic.Add("孝西", "XOV");
            dic.Add("小新街", "XXM");
            dic.Add("新兴县", "XGQ");
            dic.Add("西小召", "XZC");
            dic.Add("小西庄", "XXP");
            dic.Add("向阳", "XDB");
            dic.Add("旬阳", "XUY");
            dic.Add("旬阳北", "XBY");
            dic.Add("襄阳东", "XWN");
            dic.Add("兴业", "SNZ");
            dic.Add("小雨谷", "XHM");
            dic.Add("信宜", "EEQ");
            dic.Add("小月旧", "XFM");
            dic.Add("小扬气", "XYX");
            dic.Add("祥云", "EXM");
            dic.Add("襄垣", "EIF");
            dic.Add("夏邑县", "EJH");
            dic.Add("新友谊", "EYB");
            dic.Add("新阳镇", "XZJ");
            dic.Add("徐州东", "UUH");
            dic.Add("新帐房", "XZX");
            dic.Add("悬钟", "XRP");
            dic.Add("新肇", "XZT");
            dic.Add("忻州", "XXV");
            dic.Add("汐子", "XZD");
            dic.Add("西哲里木", "XRD");
            dic.Add("新杖子", "ERP");
            dic.Add("姚安", "YAC");
            dic.Add("依安", "YAX");
            dic.Add("永安", "YAS");
            dic.Add("永安乡", "YNB");
            dic.Add("渔坝村", "YBM");
            dic.Add("亚布力", "YBB");
            dic.Add("元宝山", "YUD");
            dic.Add("羊草", "YAB");
            dic.Add("秧草地", "YKM");
            dic.Add("阳澄湖", "AIH");
            dic.Add("迎春", "YYB");
            dic.Add("叶城", "YER");
            dic.Add("盐池", "YKJ");
            dic.Add("砚川", "YYY");
            dic.Add("阳春", "YQQ");
            dic.Add("宜城", "YIN");
            dic.Add("应城", "YHN");
            dic.Add("禹城", "YCK");
            dic.Add("晏城", "YEK");
            dic.Add("羊场", "YED");
            dic.Add("阳城", "YNF");
            dic.Add("阳岔", "YAL");
            dic.Add("郓城", "YPK");
            dic.Add("雁翅", "YAP");
            dic.Add("云彩岭", "ACP");
            dic.Add("虞城县", "IXH");
            dic.Add("营城子", "YCT");
            dic.Add("永登", "YDJ");
            dic.Add("英德", "YDQ");
            dic.Add("尹地", "YDM");
            dic.Add("永定", "YGS");
            dic.Add("雁荡山", "YGH");
            dic.Add("于都", "YDG");
            dic.Add("园墩", "YAJ");
            dic.Add("英德西", "IIQ");
            dic.Add("永福", "YFZ");
            dic.Add("永丰营", "YYM");
            dic.Add("杨岗", "YRB");
            dic.Add("阳高", "YOV");
            dic.Add("阳谷", "YIK");
            dic.Add("友好", "YOB");
            dic.Add("余杭", "EVH");
            dic.Add("沿河城", "YHP");
            dic.Add("岩会", "AEP");
            dic.Add("羊臼河", "YHM");
            dic.Add("永嘉", "URH");
            dic.Add("营街", "YAM");
            dic.Add("盐津", "AEW");
            dic.Add("余江", "YHG");
            dic.Add("叶集", "YCH");
            dic.Add("燕郊", "AJP");
            dic.Add("姚家", "YAT");
            dic.Add("岳家井", "YGJ");
            dic.Add("一间堡", "YJT");
            dic.Add("英吉沙", "YIR");
            dic.Add("云居寺", "AFP");
            dic.Add("燕家庄", "AZK");
            dic.Add("永康", "RFH");
            dic.Add("营口东", "YGT");
            dic.Add("银浪", "YJX");
            dic.Add("永郎", "YLW");
            dic.Add("宜良北", "YSM");
            dic.Add("永乐店", "YDY");
            dic.Add("伊拉哈", "YLX");
            dic.Add("伊林", "YLB");
            dic.Add("彝良", "ALW");
            dic.Add("杨林", "YLM");
            dic.Add("余粮堡", "YLD");
            dic.Add("杨柳青", "YQP");
            dic.Add("月亮田", "YUM");
            dic.Add("亚龙湾", "TWQ");
            dic.Add("杨陵镇", "YSY");
            dic.Add("义马", "YMF");
            dic.Add("云梦", "YMN");
            dic.Add("元谋", "YMM");
            dic.Add("阳明堡", "YVV");
            dic.Add("一面山", "YST");
            dic.Add("玉门镇", "YXJ");
            dic.Add("沂南", "YNK");
            dic.Add("宜耐", "YVM");
            dic.Add("伊宁东", "YNR");
            dic.Add("一平浪", "YIM");
            dic.Add("营盘水", "YZJ");
            dic.Add("羊堡", "ABM");
            dic.Add("营盘湾", "YPC");
            dic.Add("阳泉北", "YPP");
            dic.Add("乐清", "UPH");
            dic.Add("焉耆", "YSR");
            dic.Add("源迁", "AQK");
            dic.Add("姚千户屯", "YQT");
            dic.Add("阳曲", "YQV");
            dic.Add("榆树沟", "YGP");
            dic.Add("月山", "YBF");
            dic.Add("玉石", "YSJ");
            dic.Add("偃师", "YSF");
            dic.Add("沂水", "YUK");
            dic.Add("榆社", "YSV");
            dic.Add("窑上", "ASP");
            dic.Add("元氏", "YSP");
            dic.Add("杨树岭", "YAD");
            dic.Add("野三坡", "AIP");
            dic.Add("榆树屯", "YSX");
            dic.Add("榆树台", "YUT");
            dic.Add("鹰手营子", "YIP");
            dic.Add("源潭", "YTQ");
            dic.Add("牙屯堡", "YTZ");
            dic.Add("烟筒山", "YSL");
            dic.Add("烟筒屯", "YUX");
            dic.Add("羊尾哨", "YWM");
            dic.Add("越西", "YHW");
            dic.Add("攸县", "YOG");
            dic.Add("玉溪", "YXM");
            dic.Add("永修", "ACG");
            dic.Add("酉阳", "AFW");
            dic.Add("余姚", "YYH");
            dic.Add("弋阳东", "YIG");
            dic.Add("岳阳东", "YIQ");
            dic.Add("阳邑", "ARP");
            dic.Add("鸭园", "YYL");
            dic.Add("鸳鸯镇", "YYJ");
            dic.Add("燕子砭", "YZY");
            dic.Add("宜州", "YSZ");
            dic.Add("仪征", "UZH");
            dic.Add("兖州", "YZK");
            dic.Add("迤资", "YQM");
            dic.Add("羊者窝", "AEM");
            dic.Add("杨杖子", "YZD");
            dic.Add("镇安", "ZEY");
            dic.Add("治安", "ZAD");
            dic.Add("招柏", "ZBP");
            dic.Add("张百湾", "ZUP");
            dic.Add("枝城", "ZCN");
            dic.Add("子长", "ZHY");
            dic.Add("诸城", "ZQK");
            dic.Add("邹城", "ZIK");
            dic.Add("赵城", "ZCV");
            dic.Add("章党", "ZHT");
            dic.Add("肇东", "ZDB");
            dic.Add("照福铺", "ZFM");
            dic.Add("章古台", "ZGD");
            dic.Add("赵光", "ZGB");
            dic.Add("中和", "ZHX");
            dic.Add("中华门", "VNH");
            dic.Add("枝江北", "ZIN");
            dic.Add("钟家村", "ZJY");
            dic.Add("朱家沟", "ZUB");
            dic.Add("紫荆关", "ZYP");
            dic.Add("周家", "ZOB");
            dic.Add("诸暨", "ZDH");
            dic.Add("镇江南", "ZEH");
            dic.Add("周家屯", "ZOD");
            dic.Add("郑家屯", "ZJD");
            dic.Add("褚家湾", "CWJ");
            dic.Add("湛江西", "ZWQ");
            dic.Add("朱家窑", "ZUJ");
            dic.Add("曾家坪子", "ZBW");
            dic.Add("张兰", "ZLV");
            dic.Add("镇赉", "ZLT");
            dic.Add("枣林", "ZIV");
            dic.Add("扎鲁特", "ZLD");
            dic.Add("扎赉诺尔西", "ZXX");
            dic.Add("樟木头", "ZOQ");
            dic.Add("中牟", "ZGF");
            dic.Add("中宁东", "ZDJ");
            dic.Add("中宁", "VNJ");
            dic.Add("中宁南", "ZNJ");
            dic.Add("镇平", "ZPF");
            dic.Add("漳平", "ZPS");
            dic.Add("泽普", "ZPR");
            dic.Add("枣强", "ZVP");
            dic.Add("张桥", "ZQY");
            dic.Add("章丘", "ZTK");
            dic.Add("朱日和", "ZRC");
            dic.Add("泽润里", "ZLM");
            dic.Add("中山北", "ZGQ");
            dic.Add("樟树东", "ZOG");
            dic.Add("中山", "ZSQ");
            dic.Add("柞水", "ZSY");
            dic.Add("钟山", "ZSZ");
            dic.Add("樟树", "ZSG");
            dic.Add("珠窝", "ZOP");
            dic.Add("张维屯", "ZWB");
            dic.Add("彰武", "ZWD");
            dic.Add("棕溪", "ZOY");
            dic.Add("钟祥", "ZTN");
            dic.Add("资溪", "ZXS");
            dic.Add("镇西", "ZVT");
            dic.Add("张辛", "ZIP");
            dic.Add("正镶白旗", "ZXC");
            dic.Add("紫阳", "ZVY");
            dic.Add("枣阳", "ZYN");
            dic.Add("竹园坝", "ZAW");
            dic.Add("张掖", "ZYJ");
            dic.Add("镇远", "ZUW");
            dic.Add("朱杨溪", "ZXW");
            dic.Add("漳州东", "GOS");
            dic.Add("漳州", "ZUS");
            dic.Add("壮志", "ZUX");
            dic.Add("子洲", "ZZY");
            dic.Add("中寨", "ZZM");
            dic.Add("涿州", "ZXP");
            dic.Add("咋子", "ZAL");
            dic.Add("卓资山", "ZZC");
            dic.Add("株洲西", "ZAQ");
            dic.Add("许昌东", "XVF");
            dic.Add("孝感北", "XJN");
            dic.Add("邢台东", "EDP");
            dic.Add("新乡东", "EGF");
            dic.Add("西阳村", "XQF");
            dic.Add("信阳东", "OYN");
            dic.Add("雨格", "VTM");
            dic.Add("正定机场", "ZHP");
            dic.Add("织金", "IZW");
            dic.Add("驻马店西", "ZLN");
            dic.Add("涿州东", "ZAP");
            dic.Add("卓资东", "ZDC");
            dic.Add("郑州东", "ZAF");
            #endregion            
            Invoke(new Action(() => {
                lbStatusDic.Text = "字典加载成功!";
            }));
        }
        #endregion

        //处理查询出来的json字符串
        private string[] JsonHelp(string json)
        { 
            json=json.Replace("{\"validateMessagesShowId\":\"_validatorMessage\",\"status\":true,\"httpstatus\":200,\"data\":{\"datas\":[","")
                .Replace("},{","#");
            if (json.Length<=0)
            {
                Invoke(new Action(() => {
                    lbStatus.Text = "* 服务器返回错误字段";
                }));
                return null;
            }
            //提取不需要的，
            Regex r = new Regex("}],\"flag\".+");
            json = json.Replace(r.Match(json).Value, "");//将后面的一段字符串去掉

            string[] test = JsonCut(json, "#");
            return test;
        }
        #region 分割传入的json，string字符串(单层有效,可分多字符)
        /// <summary>
        /// 分割传入的json字符串
        /// </summary>
        public string[] JsonCut(string data, string strmarks)
        {
            data=data.Replace("[{","").Replace("}]","").Replace("{","").Replace("}","").Replace("\"","");
            char marks = Convert.ToChar(strmarks);
            string[] strsource = data.Split(new char[] { marks});
            return strsource;
        }
        #endregion

        //一个车票类
        public Tickets JsonTicket(string jsonPart)
        { 
            //将一个火车的json
            //train_no:550000T11640,station_train_code:T116,
            //start_station_telecode:SHH,start_station_name:上海,end_station_telecode:LZJ,end_station_name:兰州,
            //from_station_telecode:SHH,from_station_name:上海,to_station_telecode:ZZF,to_station_name:郑州,
            //start_time:15:42,arrive_time:01:44,day_difference:1,train_class_name:,lishi:10:02,
            //canWebBuy:Y,lishiValue:602,yp_info:10128530004036350000606665000510128500003023050000,control_train_day:20131230,start_train_date:20131211,seat_feature:W343631333,yp_ex:1040601030,train_seat_feature:3,seat_types:14613,location_code:H2,from_station_no:01,to_station_no:11,control_day:17,sale_time:1500,is_support_card:0,note:已售完,
            //gg_num:--,gr_num:5,qt_num:--,rw_num:无,rz_num:--,tz_num:--,wz_num:无,yb_num:--,yw_num:无,yz_num:无,ze_num:--,zy_num:--,swz_num:--
            Tickets tk = new Tickets();
            string[] lev1= JsonCut(jsonPart, ",");
            tk.train_no = JsonCut(lev1[0], ":")[1];//查询票价，预定   时候用到
            tk.station_train_code = JsonCut(lev1[1], ":")[1];
            tk.start_station_telecode = JsonCut(lev1[2], ":")[1];//查询票价  时候用到
            tk.start_station_name= JsonCut(lev1[3], ":")[1];
            tk.end_station_telecode= JsonCut(lev1[4], ":")[1];
            tk.end_station_name=JsonCut(lev1[5], ":")[1];
            tk.from_station_telecode=JsonCut(lev1[6], ":")[1];
            tk.from_station_name =JsonCut(lev1[7], ":")[1];
            tk.to_station_telecode =JsonCut(lev1[8], ":")[1];
            tk.to_station_name =JsonCut(lev1[9], ":")[1];
            tk.start_time = lev1[10].Replace("start_time:","");
            tk.arrive_time = lev1[11].Replace("arrive_time:", "");
            tk.day_difference =JsonCut(lev1[12], ":")[1];
            tk.train_class_name =JsonCut(lev1[13], ":")[1];
            tk.lishi = lev1[14].Replace("lishi:", "");
            tk.canWebBuy =JsonCut(lev1[15], ":")[1];
            tk.lishiValue =JsonCut(lev1[16], ":")[1];
            tk.yp_info =JsonCut(lev1[17], ":")[1];
            tk.control_train_day =JsonCut(lev1[18], ":")[1];
            tk.start_train_date =JsonCut(lev1[19], ":")[1];
            tk.seat_feature =JsonCut(lev1[20], ":")[1];
            tk.yp_ex =JsonCut(lev1[21], ":")[1];
            tk.train_seat_feature = JsonCut(lev1[22], ":")[1];
            tk.seat_types= JsonCut(lev1[23], ":")[1];
            tk.location_code= JsonCut(lev1[24], ":")[1];
            tk.from_station_no= JsonCut(lev1[25], ":")[1];
            tk.to_station_no= JsonCut(lev1[26], ":")[1];
            tk.control_day= JsonCut(lev1[27], ":")[1];
            tk.sale_time= JsonCut(lev1[28], ":")[1];
            tk.is_support_card= JsonCut(lev1[29], ":")[1];
            tk.note= JsonCut(lev1[30], ":")[1];
            tk.gg_num= JsonCut(lev1[31], ":")[1];
            tk.gr_num= JsonCut(lev1[32], ":")[1];
            tk.qt_num= JsonCut(lev1[33], ":")[1];
            tk.rw_num = JsonCut(lev1[34], ":")[1];
            tk.rz_num = JsonCut(lev1[35], ":")[1];
            tk.tz_num = JsonCut(lev1[36], ":")[1];
            tk.wz_num = JsonCut(lev1[37], ":")[1];
            tk.yb_num = JsonCut(lev1[38], ":")[1];
            tk.yw_num = JsonCut(lev1[39], ":")[1];
            tk.yz_num = JsonCut(lev1[40], ":")[1];
            tk.ze_num=JsonCut(lev1[41], ":")[1];
            tk.zy_num=JsonCut(lev1[42], ":")[1];
            tk.swz_num = JsonCut(lev1[43], ":")[1];
            return tk;
        }

        #region 判断网络是否连通
        [DllImport("wininet.dll")]
        private extern static bool InternetGetConnectedState(out int conn, int val);
        /// <summary>
        /// 判断网络是否连通
        /// </summary>
        /// <returns>返回1连通，0未连通</returns>
        private void InternetConState()
        {
            int Out;
            if (InternetGetConnectedState(out Out, 0) == true)
            {
                Invoke(new Action(() => {
                    lbStatusCon.Text = "网络连接正常";
                }));
            }
            else
            {                
                Invoke(new Action(() => {
                    lbStatusCon.Text = "网络尚未连接!";
                }));
            }
        }
        #endregion

        //查询票价
        //private 

    }
}
